// 自動由「★每日單字_單字卡+中翻英+英翻中.xlsx」轉出，共 1316 個單字（題號連續 1~1316，無缺漏）。
// 中文欄位保留原始格式（含詞性標籤，如 (n)(vt)(adj)），供背誦單字卡顯示用；
// 測驗批改時由 app.js 的 acceptedZhAnswers() 動態去除詞性標籤與括號註記後再比對。
const WORD_BANK_FULL = [
  { id: 1, en: "truth", zh: "真相、真理、真實性(n)" },
  { id: 2, en: "motion", zh: "運動、活動、轉動(n)" },
  { id: 3, en: "banker", zh: "銀行家(n)" },
  { id: 4, en: "noodles", zh: "麵條(n)" },
  { id: 5, en: "regular", zh: "有規律的、有規則的、定期的(adj)" },
  { id: 6, en: "channel", zh: "海峽、水渠、水道、通訊頻道(n)" },
  { id: 7, en: "humid", zh: "有濕氣的(adj)" },
  { id: 8, en: "in front of", zh: "在…的前面(片)" },
  { id: 9, en: "till", zh: "直到(…為止)(prep) 直到(…為止)(conj)" },
  { id: 10, en: "describe", zh: "形容、描寫(vt)" },
  { id: 11, en: "platform", zh: "月臺(n)" },
  { id: 12, en: "ghost", zh: "鬼(n)" },
  { id: 13, en: "pain", zh: "疼痛、痛苦、悲痛(複)辛苦(n)" },
  { id: 14, en: "owner", zh: "所有人、物主(n)" },
  { id: 15, en: "error", zh: "錯誤、誤差(n)" },
  { id: 16, en: "magazine", zh: "雜誌、期刊(n)" },
  { id: 17, en: "seesaw", zh: "蹺蹺板(n)" },
  { id: 18, en: "element", zh: "要素、元素、成分、元件、自然環境(n)" },
  { id: 19, en: "lovely", zh: "可愛的、秀美的(adj)" },
  { id: 20, en: "Dragon-boat Festival", zh: "端午節(n)" },
  { id: 21, en: "southern", zh: "南方的、南部的(adj)" },
  { id: 22, en: "baby sitter", zh: "褓母(n)" },
  { id: 23, en: "scene", zh: "(戲劇等的)一場、鏡頭、地點、背景、景色、舞臺(n)" },
  { id: 24, en: "pond", zh: "池塘(n)" },
  { id: 25, en: "Tokyo", zh: "東京(n)" },
  { id: 26, en: "arrange", zh: "安排(v)" },
  { id: 27, en: "upon", zh: "(同on)在…上、憑、靠、根據、針對(prep)" },
  { id: 28, en: "raise", zh: "舉起、提高、提升、增加、籌集、引起、飼養、提出(vt)" },
  { id: 29, en: "sneakers", zh: "膠底運動鞋(n)" },
  { id: 30, en: "purpose", zh: "目的、意圖、用途(n)" },
  { id: 31, en: "scarf", zh: "圍巾(n)" },
  { id: 32, en: "photographer", zh: "攝影師、攝影者(n)" },
  { id: 33, en: "belief", zh: "信任、信心、信仰(n)" },
  { id: 34, en: "forward", zh: "向前的、前部的(adj) 向前地、前部地(adv)" },
  { id: 35, en: "marker", zh: "作記號的人、打分數的人(n)" },
  { id: 36, en: "camping", zh: "露營(n)" },
  { id: 37, en: "clerk", zh: "店員、辦事員、職員(n)" },
  { id: 38, en: "snail", zh: "蝸牛(n)" },
  { id: 39, en: "cookies", zh: "餅乾、小甜點(n)" },
  { id: 40, en: "loss", zh: "遺失、喪失、損失、虧損(n)" },
  { id: 41, en: "decision", zh: "決定(n)" },
  { id: 42, en: "softball", zh: "壘球(n)" },
  { id: 43, en: "official", zh: "官方的、正式的(adj) 官員、行政人員(n)" },
  { id: 44, en: "as soon as", zh: "儘快(片)" },
  { id: 45, en: "Christmas Eve", zh: "聖誕前夕(n)" },
  { id: 46, en: "deny", zh: "否認、拒絕給予(vt)" },
  { id: 47, en: "dancing", zh: "跳舞(n)" },
  { id: 48, en: "courage", zh: "勇氣、膽量(n)" },
  { id: 49, en: "reach", zh: "到達、伸出(vt) 達到、延伸、伸出手(vi)" },
  { id: 50, en: "set", zh: "(一)套、副(n) 放、安置、樹立、規定、使…開始(vt)" },
  { id: 51, en: "lantern", zh: "燈籠、提燈、幻燈、信號、天窗(n)" },
  { id: 52, en: "Russia", zh: "俄羅斯(n)" },
  { id: 53, en: "inspire", zh: "鼓舞、激起、給…靈感(vt)" },
  { id: 54, en: "air conditioner", zh: "空調機(n)" },
  { id: 55, en: "eighteenth", zh: "第十八、十八分之一(n)" },
  { id: 56, en: "coin", zh: "硬幣(n)" },
  { id: 57, en: "lid", zh: "蓋子、眼臉(n)" },
  { id: 58, en: "shoes", zh: "鞋(n)" },
  { id: 59, en: "encourage", zh: "鼓勵、支援(vt)" },
  { id: 60, en: "recent", zh: "新近的、近來的(adj)" },
  { id: 61, en: "pajamas", zh: "睡衣(n)" },
  { id: 62, en: "foggy", zh: "多霧的(adj)" },
  { id: 63, en: "bar", zh: "條、棒(常用作柵欄、扣栓物) 橫木、酒吧間、柵、障礙物(n) 禁止、阻擋、妨礙、把門關住、除…之外(Bar)律師業(vt)" },
  { id: 64, en: "heater", zh: "加熱器、暖爐(n)" },
  { id: 65, en: "friendship", zh: "友誼、友情(n)" },
  { id: 66, en: "organize", zh: "組織、籌辦(vt)" },
  { id: 67, en: "conversation", zh: "談話、會話(n)" },
  { id: 68, en: "soul", zh: "靈魂、心靈(n)" },
  { id: 69, en: "yummy", zh: "好吃的、美味的(adj)" },
  { id: 70, en: "guard", zh: "看守、保衛人員、衛兵(n) 防止、防範(against)(vi)" },
  { id: 71, en: "shore", zh: "岸、濱(n)" },
  { id: 72, en: "insect", zh: "昆蟲(n)" },
  { id: 73, en: "crime", zh: "犯罪、罪行、罪惡(n)" },
  { id: 74, en: "war", zh: "戰爭、鬥爭(n)" },
  { id: 75, en: "toward", zh: "(表示方向)朝、向(prep)" },
  { id: 76, en: "fishing", zh: "釣魚(n)" },
  { id: 77, en: "twentieth", zh: "第二十(num) 二十分之一(n)" },
  { id: 78, en: "Mother's Day", zh: "母親節(n)" },
  { id: 79, en: "ox", zh: "公牛、牛(n)" },
  { id: 80, en: "coast", zh: "海岸、海濱(n)" },
  { id: 81, en: "pollution", zh: "污染(n)" },
  { id: 82, en: "earn", zh: "賺得、獲得、掙得(vt)" },
  { id: 83, en: "department", zh: "部門、部、院、局、處(n)" },
  { id: 84, en: "auxiliary", zh: "輔助的、協助的(adj) 輔助物、援軍(n)" },
  { id: 85, en: "assistant", zh: "助手、助理、助教(n) 助手的、輔助的(adj)" },
  { id: 86, en: "photo", zh: "相片(n)" },
  { id: 87, en: "neighbor", zh: "鄰居(n)" },
  { id: 88, en: "lot", zh: "許多、大量、命運(n)" },
  { id: 89, en: "drinks", zh: "飲料(n)" },
  { id: 90, en: "puppy", zh: "小狗(n)" },
  { id: 91, en: "lamb", zh: "小羊(肉) 羔羊(肉)(n)" },
  { id: 92, en: "university", zh: "大學(n)" },
  { id: 93, en: "memory", zh: "記憶、記憶力、回憶、紀念(n)" },
  { id: 94, en: "mountain-climbing", zh: "登山、爬山(n)" },
  { id: 95, en: "bow", zh: "弓(形物) 蝴蝶結(n) 鞠躬、點頭(n)" },
  { id: 96, en: "barbecue", zh: "吃烤燒肉的野餐(n)" },
  { id: 97, en: "swan", zh: "天鵝(n)" },
  { id: 98, en: "standard", zh: "標準、規格(n) 標準的(adj)" },
  { id: 99, en: "tie", zh: "拴、紮、捆、繫上(vt) 領帶、領結、聯繫(n)" },
  { id: 100, en: "failure", zh: "失敗、失敗者、缺乏、失靈、故障、破產、疏忽(美)不及格(n)" },
  { id: 101, en: "amount", zh: "合計(vi)" },
  { id: 102, en: "washing machine", zh: "洗衣機(n)" },
  { id: 103, en: "apply", zh: "申請(vi) 應用(vt)" },
  { id: 104, en: "judge", zh: "法官、審判者(n) 評定、斷定、判斷、審判(vt)" },
  { id: 105, en: "Canadian", zh: "加拿大人(n)" },
  { id: 106, en: "garage", zh: "車庫(n)" },
  { id: 107, en: "seem", zh: "好像、似乎(vi)" },
  { id: 108, en: "golf", zh: "高爾夫(n)" },
  { id: 109, en: "subway", zh: "地鐵(n)" },
  { id: 110, en: "exercising", zh: "運動、體操(n)" },
  { id: 111, en: "fast food restaurant", zh: "速食餐廳(n)" },
  { id: 112, en: "singing", zh: "(歌)唱、歌聲(n)" },
  { id: 113, en: "VCR", zh: "錄影機(n)" },
  { id: 114, en: "function", zh: "官能、功能、作用、職責、典禮、儀式、[數]函數(n)(器官等)活動、運行、行使職責(vi)" },
  { id: 115, en: "deaf", zh: "聾的、不願聽的(adj)" },
  { id: 116, en: "bundle", zh: "包、捆、束(n) 包紮、捆(v)" },
  { id: 117, en: "generally", zh: "一般地(adv)" },
  { id: 118, en: "pineapple", zh: "鳳梨(n)" },
  { id: 119, en: "cabinet", zh: "(有抽屜或格子的)櫥櫃(美)內閣(n)(美)內閣的、小巧的(adj)" },
  { id: 120, en: "traffic sign", zh: "交通號誌(n)" },
  { id: 121, en: "tower", zh: "塔(樓)(n)" },
  { id: 122, en: "humorous", zh: "幽默的、詼諧的(adj)" },
  { id: 123, en: "fry", zh: "煎、炸、炒(v)" },
  { id: 124, en: "tape recorder", zh: "錄音機(n)" },
  { id: 125, en: "affect", zh: "影響(v)" },
  { id: 126, en: "rapid", zh: "快的、迅速的(adj)" },
  { id: 127, en: "interrupt", zh: "打斷、打擾、中止(vt)" },
  { id: 128, en: "kitten", zh: "小貓、頑皮的女孩(n)" },
  { id: 129, en: "carrot", zh: "胡蘿蔔(n)" },
  { id: 130, en: "goose", zh: "鵝(n)" },
  { id: 131, en: "kingdom", zh: "王國(n)" },
  { id: 132, en: "row", zh: "(一)排、行、列(n) 划船(v)" },
  { id: 133, en: "outer space", zh: "外太空、星際空間(n)" },
  { id: 134, en: "surface", zh: "表面、面、外表、外觀(n)" },
  { id: 135, en: "root", zh: "根(部)(n)" },
  { id: 136, en: "sort", zh: "種類、類別(n) 分類、整理(vt)" },
  { id: 137, en: "not only xxx but also", zh: "不僅…而且…" },
  { id: 138, en: "musician", zh: "音樂家(n)" },
  { id: 139, en: "rope", zh: "繩、索(n)" },
  { id: 140, en: "control", zh: "控制、支配、克制(vt) 控制、克制(n)" },
  { id: 141, en: "hey", zh: "嘿、喂(interj)" },
  { id: 142, en: "press", zh: "壓、按、壓迫、壓榨、逼迫(vt) 壓、按、報刊、出版社、新聞界(n)" },
  { id: 143, en: "pronoun", zh: "代名詞(n)" },
  { id: 144, en: "hammer", zh: "槌、榔頭、槌狀物(n)" },
  { id: 145, en: "under-weight", zh: "重量不足(adj)" },
  { id: 146, en: "rude", zh: "無禮的、野蠻的(adj)" },
  { id: 147, en: "strike", zh: "打、襲擊、使突然想到、給…留下印象(vt) 罷工(鐘等)敲響(vi)" },
  { id: 148, en: "dumpling", zh: "餃子(n)" },
  { id: 149, en: "strawberry", zh: "草莓(n)" },
  { id: 150, en: "operate", zh: "運行、運轉、手術(vi) 操作、操縱、進行(vt)" },
  { id: 151, en: "include", zh: "包括、包含(vt)" },
  { id: 152, en: "childhood", zh: "孩童時期(n)" },
  { id: 153, en: "generous", zh: "慷慨的、大方的、寬厚的(adj)" },
  { id: 154, en: "progress", zh: "前進、進步、進展(n) 前進、進步、進展(vi)" },
  { id: 155, en: "shine", zh: "照耀、發光、發亮、閃耀(v)" },
  { id: 156, en: "electric", zh: "電的、電動的(adj)" },
  { id: 157, en: "alphabet", zh: "字母、字母表(n)" },
  { id: 158, en: "pile", zh: "一堆、一疊(n) 把…堆積(v)" },
  { id: 159, en: "diet", zh: "通常所吃的食物、會議(n)" },
  { id: 160, en: "thumb", zh: "拇指(n)" },
  { id: 161, en: "promise", zh: "允諾、答應(vt) 允諾、有指望(vi)" },
  { id: 162, en: "stationery store", zh: "文具店(n)" },
  { id: 163, en: "success", zh: "成就、成功(n)" },
  { id: 164, en: "swing", zh: "搖擺、盪鞦韆、迴旋(v)" },
  { id: 165, en: "soft", zh: "軟的、溫柔的、不含酒精的(adj)" },
  { id: 166, en: "Italy", zh: "義大利(n)" },
  { id: 167, en: "diligent", zh: "勤奮的、煞費苦心的(adj)" },
  { id: 168, en: "thought", zh: "思想(n)" },
  { id: 169, en: "stomachache", zh: "肚子痛、胃痛(n)" },
  { id: 170, en: "calm", zh: "平靜的、鎮靜的(adj) 使…平靜/鎮定(vt)" },
  { id: 171, en: "board", zh: "(木)板、董事會(n) 上(車、船或飛機)(vt)" },
  { id: 172, en: "voter", zh: "投票者、有投票權者(n)" },
  { id: 173, en: "rub", zh: "摩擦、擦拭(v)" },
  { id: 174, en: "data", zh: "[計]資料(n)" },
  { id: 175, en: "fantastic", zh: "幻想的、奇異的、稀奇古怪的、荒謬的、空想的(adj)" },
  { id: 176, en: "eastern", zh: "東方的、東部的(adj)" },
  { id: 177, en: "dot", zh: "點(n)" },
  { id: 178, en: "neither xxx nor", zh: "既不…也不…(片)" },
  { id: 179, en: "western", zh: "西的、西方的、來自西方的人、有西方特徵的(adj)" },
  { id: 180, en: "reflexive", zh: "反身代名詞(n)" },
  { id: 181, en: "bicycle riding", zh: "騎腳踏車(n)" },
  { id: 182, en: "balcony", zh: "陽臺(n)" },
  { id: 183, en: "drawing", zh: "畫畫、圖畫、素描(n)" },
  { id: 184, en: "liquid", zh: "液體的、流動性的(adj)" },
  { id: 185, en: "income", zh: "收入、收益、所得(n)" },
  { id: 186, en: "willing", zh: "願意的、樂意的、心甘情願的(adj)" },
  { id: 187, en: "hardly", zh: "簡直不、幾乎不(adv)" },
  { id: 188, en: "single", zh: "單一的、單個的、單身的、未婚的(adj)" },
  { id: 189, en: "England", zh: "英格蘭、英國(n)" },
  { id: 190, en: "explain", zh: "解釋、說明(vt)" },
  { id: 191, en: "science", zh: "科學、學科(n)" },
  { id: 192, en: "as well as", zh: "也、不僅…而且(片)" },
  { id: 193, en: "advantage", zh: "優勢、有利條件、利益(n)" },
  { id: 194, en: "roll", zh: "(使…)滾動、轉動、碾、軋、卷、繞(v)(一)卷、麵包卷(n)" },
  { id: 195, en: "curious", zh: "好奇的(adj)" },
  { id: 196, en: "prince", zh: "王子、皇太子、親王(n)" },
  { id: 197, en: "awake", zh: "喚醒、使…覺醒(vt)" },
  { id: 198, en: "democracy", zh: "民主政治、民主主義(n)" },
  { id: 199, en: "iron", zh: "鐵、熨斗(n) 熨、燙(vt)" },
  { id: 200, en: "assume", zh: "假定、設想(vt)" },
  { id: 201, en: "production", zh: "生產、產量、產品(n)" },
  { id: 202, en: "safety", zh: "安全、平安(n)" },
  { id: 203, en: "cassette", zh: "(裝錄音帶的)卡式盒(匣)(n)" },
  { id: 204, en: "narrow", zh: "狹窄的(adj)" },
  { id: 205, en: "environment", zh: "環境、周圍狀況(n)" },
  { id: 206, en: "rubber", zh: "橡皮、橡膠(製品)(複)膠鞋(n)" },
  { id: 207, en: "French", zh: "法國的、法國人的(adj)(總稱)法國人、法語(n)" },
  { id: 208, en: "Asia", zh: "亞洲(n)" },
  { id: 209, en: "career", zh: "(原意:道路、軌道)事業、生涯、速度(n)" },
  { id: 210, en: "election", zh: "選舉、當選(n)" },
  { id: 211, en: "police station", zh: "警察局(n)" },
  { id: 212, en: "double", zh: "兩倍的、雙(重)的(adj)(使…)加倍(v)" },
  { id: 213, en: "careless", zh: "不注意的、粗心大意的(adj)" },
  { id: 214, en: "leaf", zh: "葉子(書刊的)張、頁(n)(複:leaves)" },
  { id: 215, en: "skiing", zh: "滑雪(運動) 滑雪技術(n)" },
  { id: 216, en: "attend", zh: "出席(v)" },
  { id: 217, en: "suddenly", zh: "突然地(adv)" },
  { id: 218, en: "flight", zh: "飛翔、飛行、航班(n)" },
  { id: 219, en: "action", zh: "動作、行動(n)" },
  { id: 220, en: "hero", zh: "英雄、男主角、男主人(n)" },
  { id: 221, en: "generation", zh: "代、輩、產生、發生(n)" },
  { id: 222, en: "over-weight", zh: "超重(n)" },
  { id: 223, en: "comfortably", zh: "舒適地(adv)" },
  { id: 224, en: "material", zh: "材料、原料(n) 物質的、實體的(adj)" },
  { id: 225, en: "praise", zh: "稱讚、表揚(n) 讚揚、表揚、吹捧(vt)" },
  { id: 226, en: "Japan", zh: "日本(n)" },
  { id: 227, en: "design", zh: "設計(v) 設計、圖樣、圖案(n)" },
  { id: 228, en: "childlike", zh: "孩子似的、天真無邪的(adj)" },
  { id: 229, en: "screen", zh: "螢幕、屏風、簾(n) 掩蔽、遮蔽(vt)" },
  { id: 230, en: "clothing", zh: "(總稱)衣服(n)" },
  { id: 231, en: "waste", zh: "浪費、毀壞(v)" },
  { id: 232, en: "pump", zh: "抽水機、幫浦(n)" },
  { id: 233, en: "topic", zh: "題目、話題、主題(n)" },
  { id: 234, en: "active", zh: "活躍的、積極的(adj)" },
  { id: 235, en: "being be", zh: "的現在分詞(v) 存在、生存(n)" },
  { id: 236, en: "candle", zh: "蠟燭(n)" },
  { id: 237, en: "trade", zh: "貿易、商業、行業、職業(n) 相互交換(vt)" },
  { id: 238, en: "record", zh: "記錄、記載、唱片(n) 記錄、記載、錄下(vt)" },
  { id: 239, en: "stamp collecting", zh: "集郵(n)" },
  { id: 240, en: "influence", zh: "影響、感化力(adj) 影響(vt)" },
  { id: 241, en: "feather", zh: "羽毛(n)" },
  { id: 242, en: "biology", zh: "生物學、生物(總稱)(n)" },
  { id: 243, en: "ocean", zh: "洋、海洋(n)" },
  { id: 244, en: "microwave", zh: "微波(n)" },
  { id: 245, en: "argue", zh: "爭論、爭辯(vi) 論證、主張、辯論(vt)" },
  { id: 246, en: "god", zh: "神(God)上帝(n)" },
  { id: 247, en: "microwave oven", zh: "微波爐(n)" },
  { id: 248, en: "poem", zh: "詩(n)" },
  { id: 249, en: "throat", zh: "咽喉、喉嚨(n)" },
  { id: 250, en: "ability", zh: "能力、才幹(n)" },
  { id: 251, en: "Kaohsiung", zh: "高雄(n)" },
  { id: 252, en: "traffic light", zh: "交通燈號誌(n)" },
  { id: 253, en: "skillful", zh: "靈巧的、熟練的、製作精巧的(adj)" },
  { id: 254, en: "cotton", zh: "棉花、棉布(n)" },
  { id: 255, en: "uh-uh", zh: "嗯嗯(interj)" },
  { id: 256, en: "speed", zh: "速度、迅速(n) 迅速前進、加速、加快(vi)" },
  { id: 257, en: "trash can", zh: "垃圾桶(n)" },
  { id: 258, en: "adjective", zh: "形容詞的(adj)" },
  { id: 259, en: "skinny", zh: "皮的、皮質的、骨瘦如材的(adj)" },
  { id: 260, en: "beginning", zh: "開始、起源(n)" },
  { id: 261, en: "bat", zh: "蝙蝠(n)" },
  { id: 262, en: "sour", zh: "酸的(adj)" },
  { id: 263, en: "fault", zh: "過失、過錯、缺點、故障(n)" },
  { id: 264, en: "onion", zh: "洋蔥(n)" },
  { id: 265, en: "increase", zh: "(使…)增加、增長(v) 增加、增長(n)" },
  { id: 266, en: "bark", zh: "(狗等)吠、叫(vi) 大聲叫喊(vt)" },
  { id: 267, en: "film", zh: "電影、影片、膠捲、膠片(n) 把…拍攝成電影(vt)" },
  { id: 268, en: "area", zh: "地區、地域、範圍、面積(n)" },
  { id: 269, en: "middle", zh: "中間、中部(n) 中間的、中央的(adj)" },
  { id: 270, en: "humble", zh: "謙遜的、謙恭的、地位低下的、卑賤的(adj)" },
  { id: 271, en: "fail", zh: "失敗、不及格、失靈(vi) 不、未能、使…不及格(vt)" },
  { id: 272, en: "cause", zh: "原因、起因、事業(n) 使…產生、引起(vt)" },
  { id: 273, en: "thief", zh: "小偷、賊(n)" },
  { id: 274, en: "weight", zh: "重量、體重(n)" },
  { id: 275, en: "plastic", zh: "塑膠的(adj)" },
  { id: 276, en: "post", zh: "張貼、公告(n) 支柱、標桿、職位(vt)" },
  { id: 277, en: "stairs", zh: "樓梯(n)" },
  { id: 278, en: "nation", zh: "國家、民族(n)" },
  { id: 279, en: "nest", zh: "巢、窩、穴、窟(n)" },
  { id: 280, en: "dumb", zh: "啞的(adj)" },
  { id: 281, en: "in back of", zh: "在(某人)之後、背地裡、暗中(片)" },
  { id: 282, en: "gentleman", zh: "先生、紳士(n)" },
  { id: 283, en: "entrance", zh: "入口、門口(n)" },
  { id: 284, en: "winner", zh: "贏家、勝利者(n)" },
  { id: 285, en: "mechanic", zh: "機械工、技工(n)" },
  { id: 286, en: "brunch", zh: "早午餐(n)" },
  { id: 287, en: "adverb", zh: "副詞(n)" },
  { id: 288, en: "beard", zh: "鬍鬚、倒鉤(n)" },
  { id: 289, en: "basement", zh: "地下室(n)" },
  { id: 290, en: "trick", zh: "欺詐、哄騙(vt) 詭計、花招、把戲、戲法、惡作劇(n)" },
  { id: 291, en: "hippo", zh: "河馬(n)" },
  { id: 292, en: "noisy", zh: "喧鬧的(adj)" },
  { id: 293, en: "aware", zh: "意識到(adj)" },
  { id: 294, en: "guest", zh: "客人、旅客(n)" },
  { id: 295, en: "rubber band", zh: "橡皮筋(n)" },
  { id: 296, en: "as if", zh: "好像(片)" },
  { id: 297, en: "LD", zh: "雷射光碟(n)" },
  { id: 298, en: "term", zh: "學期、期限、期間、術語(n)" },
  { id: 299, en: "rather", zh: "相當、有一點兒、寧願(adv)" },
  { id: 300, en: "figure", zh: "數字、外形、輪廓、人物、體形、身材、插圖(n)" },
  { id: 301, en: "refuse", zh: "拒絕、謝絕(v)" },
  { id: 302, en: "wedding", zh: "婚禮(n)" },
  { id: 303, en: "secondary", zh: "第二的、次等的(adj)" },
  { id: 304, en: "advance", zh: "前進、向前移動(vi) 前進、進展(n)" },
  { id: 305, en: "Rome", zh: "羅馬(n)" },
  { id: 306, en: "citizen", zh: "公民、市民、居民(n)" },
  { id: 307, en: "daily", zh: "每日的(adj) 每日、天天(adv)" },
  { id: 308, en: "weekday", zh: "周一到周五的通稱(n)" },
  { id: 309, en: "seafood", zh: "海鮮(n)" },
  { id: 310, en: "nice looking", zh: "美貌的、漂亮的、英俊的(adj)" },
  { id: 311, en: "chubby", zh: "胖嘟嘟的、圓胖的(adj)" },
  { id: 312, en: "marriage", zh: "結婚、婚姻(n)" },
  { id: 313, en: "altogether", zh: "總共、完全、總之(adv)" },
  { id: 314, en: "melon", zh: "(各種的)瓜(n)" },
  { id: 315, en: "Teacher's Day", zh: "教師節(n)" },
  { id: 316, en: "swimsuit", zh: "游泳衣、泳裝(n)" },
  { id: 317, en: "affair", zh: "事情、事件(n)" },
  { id: 318, en: "photograph", zh: "照片(n)" },
  { id: 319, en: "mud", zh: "泥(n)" },
  { id: 320, en: "customer", zh: "顧客、主顧(n)" },
  { id: 321, en: "professor", zh: "教授(n)" },
  { id: 322, en: "apologize", zh: "道歉、認錯(vi)" },
  { id: 323, en: "silent", zh: "寂靜的、沈默的(adj)" },
  { id: 324, en: "force", zh: "強迫、迫使(vt) 暴力、武力、力氣(複)軍隊(n)" },
  { id: 325, en: "continue", zh: "繼續、延續(v)" },
  { id: 326, en: "pepper", zh: "胡椒粉(n)" },
  { id: 327, en: "honesty", zh: "正直、誠實、老實(n)" },
  { id: 328, en: "empty", zh: "空的、空洞的、空虛的(adj) 使…空、倒空(v)" },
  { id: 329, en: "vinegar", zh: "醋(n)" },
  { id: 330, en: "princess", zh: "公主、王妃、親王夫人(n)" },
  { id: 331, en: "traveling", zh: "旅行的、遊歷的(adj)" },
  { id: 332, en: "decorate", zh: "裝飾、裝璜(vt)" },
  { id: 333, en: "particular", zh: "特定的、某一的、挑剔的、特別的(adj)" },
  { id: 334, en: "conflict", zh: "衝突(vi) 爭論、衝突(n)" },
  { id: 335, en: "anyway", zh: "無論如何(adv)" },
  { id: 336, en: "actor", zh: "男演員(n)" },
  { id: 337, en: "teapot", zh: "茶壺(n)" },
  { id: 338, en: "airmail", zh: "航空信(n)" },
  { id: 339, en: "housewife", zh: "家庭婦女(n)" },
  { id: 340, en: "distance", zh: "距離、間距(n)" },
  { id: 341, en: "danger", zh: "危險(n)" },
  { id: 342, en: "backward", zh: "向後地(的) 相反地(的) 追溯、退步、由好變壞(adv) 向後地(的) 相反地(的) 追溯、退步、由好變壞(adj)" },
  { id: 343, en: "tofu", zh: "豆腐(n)" },
  { id: 344, en: "mass", zh: "眾多、大量、團、塊(n)" },
  { id: 345, en: "improve", zh: "改善、改進(vt) 改善、好轉(vi)" },
  { id: 346, en: "invent", zh: "發明、創造(v)" },
  { id: 347, en: "nationality", zh: "國民性、國籍、國民(n)" },
  { id: 348, en: "corner", zh: "角、牆角、街角(n)" },
  { id: 349, en: "balloon", zh: "氣球(n)" },
  { id: 350, en: "even if", zh: "即使、縱然(片)" },
  { id: 351, en: "pencil case", zh: "鉛筆盒(n)" },
  { id: 352, en: "succeed", zh: "成功、接著發生、繼承(vi) 接替、接…之後(vt)" },
  { id: 353, en: "reject", zh: "拒絕、駁回、捨棄(vt)" },
  { id: 354, en: "note", zh: "便條、筆記、註解、票據(n) 記錄、留意(vt)" },
  { id: 355, en: "advice", zh: "勸告、意見(n)" },
  { id: 356, en: "dentist", zh: "牙醫(n)" },
  { id: 357, en: "cartoon", zh: "(報刊上的)政治性漫畫、諷刺畫、卡通畫、漫畫(常有解說詞)(n) 卡通片、動畫片(n)" },
  { id: 358, en: "probably", zh: "大概、或許、很可能(adv)" },
  { id: 359, en: "class leader", zh: "班長(n)" },
  { id: 360, en: "greedy", zh: "貪食的、貪婪的、貪心的(adj)" },
  { id: 361, en: "Lantern Festival", zh: "元宵節(n)" },
  { id: 362, en: "total", zh: "總計(v)" },
  { id: 363, en: "require", zh: "需要、規定、要求(vt)" },
  { id: 364, en: "worried", zh: "煩惱的、擔心的(adj)" },
  { id: 365, en: "roof", zh: "屋頂(n)" },
  { id: 366, en: "peace", zh: "和平、和睦、平靜(n)" },
  { id: 367, en: "subject", zh: "主題、題目、學科、主語(語法用語)(n) 易遭…的、受…支配(adj)" },
  { id: 368, en: "football", zh: "足球、足球運動(n)" },
  { id: 369, en: "slide", zh: "滑行、滑動、偷溜(v)" },
  { id: 370, en: "honey", zh: "蜂蜜、花蜜、親愛的(n)" },
  { id: 371, en: "cash", zh: "現金(n)" },
  { id: 372, en: "straight", zh: "直的、筆直的、直接了當的(adj) 直接、一直、立即(adv)" },
  { id: 373, en: "wave", zh: "揮動、向…揮手示意(vt) 浪、波濤(光、電等的)波(n)" },
  { id: 374, en: "sincere", zh: "真誠的、誠摯的、衷心的(adj)" },
  { id: 375, en: "ahead", zh: "在前、向前、提前(adv)" },
  { id: 376, en: "satisfy", zh: "使…滿足、使…滿意(vt)" },
  { id: 377, en: "given name", zh: "名字、教名(n)" },
  { id: 378, en: "centimeter", zh: "釐米、公分(n)" },
  { id: 379, en: "dodge ball", zh: "躲避球(n)" },
  { id: 380, en: "receive", zh: "接見、接收(v)" },
  { id: 381, en: "develop", zh: "發展、形成、開發(vt) 發展、成長、發育(vi)" },
  { id: 382, en: "century", zh: "世紀、百年(n)" },
  { id: 383, en: "turkey", zh: "火雞(n)" },
  { id: 384, en: "position", zh: "位置、職位、姿勢、見解、立場(n)" },
  { id: 385, en: "information", zh: "消息、情報、資訊(n)" },
  { id: 386, en: "event", zh: "事件、大事(n)" },
  { id: 387, en: "respect", zh: "尊敬、尊重(vt) 尊重、敬意(複)敬意(n)" },
  { id: 388, en: "grapefruit", zh: "葡萄柚(樹)(n)" },
  { id: 389, en: "shout", zh: "呼喊、呼叫(v) 呼喊、呼叫(n)" },
  { id: 390, en: "population", zh: "人口(n)" },
  { id: 391, en: "drugstore", zh: "藥局(n)" },
  { id: 392, en: "deliver", zh: "投遞、發表、分娩(vt)" },
  { id: 393, en: "excite", zh: "使…興奮、使…激動(vt)" },
  { id: 394, en: "engine", zh: "引擎(n)" },
  { id: 395, en: "priest", zh: "僧侶、牧師、神職者(n)" },
  { id: 396, en: "relative", zh: "相對的(adj) 親戚(n)" },
  { id: 397, en: "reason", zh: "理由、原因、理性(n) 推理(vt)" },
  { id: 398, en: "pop music", zh: "流行音樂(n)" },
  { id: 399, en: "dresser", zh: "碗櫃、餐具櫥、服裝師(n)" },
  { id: 400, en: "flag", zh: "旗(幟)(n)" },
  { id: 401, en: "wide", zh: "寬闊的、廣泛的(adj) 全部地、充分地(adv)" },
  { id: 402, en: "exact", zh: "精確的、確切的(adj)" },
  { id: 403, en: "album", zh: "相簿(n)" },
  { id: 404, en: "soda", zh: "汽水(n)" },
  { id: 405, en: "precious", zh: "珍貴的、寶貴的(adj)" },
  { id: 406, en: "hairdresser", zh: "美髮師(n)" },
  { id: 407, en: "overseas", zh: "(在)海外的;(在)國外的(adj) 在(或向)海外;在(或向)國外(adv)" },
  { id: 408, en: "sore throat", zh: "喉嚨痛(n)" },
  { id: 409, en: "wound", zh: "創傷、傷口(n) 使受傷、傷害(vt)" },
  { id: 410, en: "cloth", zh: "布、布料、抹布、桌布(n)" },
  { id: 411, en: "admit", zh: "承認、准許…進入、准許…加入(vt)" },
  { id: 412, en: "guitar", zh: "吉他(n)" },
  { id: 413, en: "cure", zh: "治癒、消除、改正(vt) 治癒、治療(n)" },
  { id: 414, en: "impossible", zh: "不可能的、辦不到的(adj)" },
  { id: 415, en: "CD", zh: "光碟(Compact Disk 縮寫)(n) 雷射唱片(n)" },
  { id: 416, en: "partner", zh: "搭檔、夥伴(n)" },
  { id: 417, en: "determiner", zh: "(文法的)限定詞(n)" },
  { id: 418, en: "trousers", zh: "褲子、長褲(n)" },
  { id: 419, en: "wrist", zh: "手腕(n)" },
  { id: 420, en: "concern", zh: "關心、掛念(n) 涉及、使關心、掛念(vt)" },
  { id: 421, en: "scared", zh: "驚嚇的、受驚的、恐懼的(adj)" },
  { id: 422, en: "blanket", zh: "毯子(n)" },
  { id: 423, en: "congratulation", zh: "祝賀、恭賀(n)" },
  { id: 424, en: "bill", zh: "帳單、單子、清單、鈔票、喙、鳥嘴(n)" },
  { id: 425, en: "regret", zh: "遺憾、後悔(n) 遺憾、後悔(v)" },
  { id: 426, en: "alive", zh: "活著的、存在的、活躍的(adj)" },
  { id: 427, en: "next to", zh: "緊挨著(片)" },
  { id: 428, en: "damage", zh: "毀壞、損害(vt) 毀壞(複)賠償金(n)" },
  { id: 429, en: "accept", zh: "接受、認可(vt)" },
  { id: 430, en: "wallet", zh: "錢包、皮夾(n)" },
  { id: 431, en: "peach", zh: "桃子、桃色(n)" },
  { id: 432, en: "neither", zh: "也不(conj、 adv) 兩者皆不的(adj)" },
  { id: 433, en: "social science", zh: "社會科學(n)" },
  { id: 434, en: "soccer", zh: "(英式)足球(n)" },
  { id: 435, en: "independent", zh: "獨立的、自主的、自食其力的(adj)" },
  { id: 436, en: "passenger", zh: "乘客、旅客(n)" },
  { id: 437, en: "effort", zh: "努力、艱難的嘗試(n)" },
  { id: 438, en: "spirit", zh: "精神、氣概、志氣;(複)心情、烈灑(n)" },
  { id: 439, en: "bowling", zh: "保齡球(n)" },
  { id: 440, en: "swallow", zh: "吞咽(v) 燕子(n)" },
  { id: 441, en: "stick", zh: "捧、手杖(n) 刺、戳、黏貼(vt)(pt&pp:stuck)" },
  { id: 442, en: "quiz", zh: "測驗(n)" },
  { id: 443, en: "flat tire", zh: "洩了氣的輪胎(n)" },
  { id: 444, en: "prison", zh: "監獄(n)" },
  { id: 445, en: "forest", zh: "森林(n)" },
  { id: 446, en: "discuss", zh: "討論(v)" },
  { id: 447, en: "match", zh: "火柴、比賽(n)" },
  { id: 448, en: "society", zh: "社會、社、團體、協會(n)" },
  { id: 449, en: "occur", zh: "發生、出現、浮現(vi)" },
  { id: 450, en: "tunnel", zh: "隧道、地道、坑道(n)" },
  { id: 451, en: "solve", zh: "解釋、說明、解決(v)" },
  { id: 452, en: "death", zh: "死、死亡(n)" },
  { id: 453, en: "pardon", zh: "原諒、饒恕(vt) 原諒、對不起(n)" },
  { id: 454, en: "ankle", zh: "踝(n)" },
  { id: 455, en: "buffet", zh: "自助餐廳(n) 打擊、毆打(v)" },
  { id: 456, en: "mask", zh: "面具、面罩、口罩(n) 面具遮住、遮蓋(vt)" },
  { id: 457, en: "European", zh: "歐洲的(adj) 歐洲人(n)" },
  { id: 458, en: "movie theater", zh: "電影院(n)" },
  { id: 459, en: "Germany", zh: "德國(n)" },
  { id: 460, en: "bake", zh: "烘、烤(vt)" },
  { id: 461, en: "airline", zh: "航線(n)" },
  { id: 462, en: "drug", zh: "藥、藥物;(複)毒品、麻醉藥品(n) 用藥麻醉(vt)" },
  { id: 463, en: "Michael Jackson", zh: "麥可傑克森(人名)(n)" },
  { id: 464, en: "schoolmate", zh: "校友(n)" },
  { id: 465, en: "army", zh: "軍隊、軍(n)" },
  { id: 466, en: "message", zh: "訊息、文電、便條、口信(n)" },
  { id: 467, en: "patient", zh: "忍耐的、有耐心的(adj) 病人(n)" },
  { id: 468, en: "carpet", zh: "地毯(n)" },
  { id: 469, en: "thunder", zh: "雷(n) 打雷(v)" },
  { id: 470, en: "guy", zh: "男人、傢伙、人(n)" },
  { id: 471, en: "chart", zh: "海圖、圖表(n) 製圖(vt)" },
  { id: 472, en: "bitter", zh: "痛苦的、有苦味的、寒冷入骨的(adj)" },
  { id: 473, en: "reading test", zh: "閱讀測驗(n)" },
  { id: 474, en: "ugly", zh: "醜陋的、難看的、難聽的(adj)" },
  { id: 475, en: "supper", zh: "晚餐(n)" },
  { id: 476, en: "food restaurant", zh: "餐廳(n)" },
  { id: 477, en: "pray", zh: "請求、懇求、祈求(v)" },
  { id: 478, en: "guava", zh: "蕃石榴(n)" },
  { id: 479, en: "moon cake", zh: "月餅(n)" },
  { id: 480, en: "yucky", zh: "令人厭惡的(adj)" },
  { id: 481, en: "forgive", zh: "原諒(v)" },
  { id: 482, en: "typewriter", zh: "打字機(n)" },
  { id: 483, en: "object", zh: "物體、實物、目的、目標、物件(n) 反對、不贊成(vi)" },
  { id: 484, en: "faucet", zh: "(容器或水管的)龍頭(n)" },
  { id: 485, en: "shelf", zh: "棚、架(n)" },
  { id: 486, en: "discover", zh: "發現、暴露、顯示(v)" },
  { id: 487, en: "similar", zh: "相似的、類似的(to)(adj)" },
  { id: 488, en: "task", zh: "任務、工作(n)" },
  { id: 489, en: "Britain", zh: "英國(n)" },
  { id: 490, en: "aloud", zh: "出聲地、大聲地(adv)" },
  { id: 491, en: "state", zh: "狀態、情況、國家、州(n)" },
  { id: 492, en: "coach", zh: "長途公共汽車、車廂、教練(n) 訓練、指導(vt)" },
  { id: 493, en: "overpass", zh: "陸橋、高架道路、立體交叉道路(n) 超越、越過、漏看(v)" },
  { id: 494, en: "create", zh: "創造、創作(v)" },
  { id: 495, en: "freedom", zh: "自由(n)" },
  { id: 496, en: "violin", zh: "小提琴(n)" },
  { id: 497, en: "button", zh: "鈕扣、按扭(n) 扣上、扣緊(vt)" },
  { id: 498, en: "CD player", zh: "雷射唱片播放器(n)" },
  { id: 499, en: "separate", zh: "分離的、分開的(adj)(使…)分開、分離(v)" },
  { id: 500, en: "elect", zh: "選舉、選擇、決定(v)" },
  { id: 501, en: "downstairs", zh: "樓下(的)(n)" },
  { id: 502, en: "movement", zh: "運動、活動、移動(n)" },
  { id: 503, en: "corn", zh: "穀物、小麥、玉米(n)" },
  { id: 504, en: "effect", zh: "結果、效果、作用(n) 引起、招致(vt)" },
  { id: 505, en: "trap", zh: "陷阱、圈套、詭計(n)" },
  { id: 506, en: "hiking", zh: "步行、遠足、徒步旅行(n)" },
  { id: 507, en: "Hong Kong", zh: "香港(n)" },
  { id: 508, en: "add", zh: "(添)加、進一步說(或寫)(vt) 增添(vi)" },
  { id: 509, en: "glue", zh: "膠水(n)" },
  { id: 510, en: "prisoner", zh: "囚犯(n)" },
  { id: 511, en: "chairman", zh: "主席、議長、董事長(n)" },
  { id: 512, en: "drawer", zh: "付款人、製圖者(n)" },
  { id: 513, en: "step", zh: "步、腳步、步驟、臺階(n) 跨步、行走、踩、踏上(on)(vi)" },
  { id: 514, en: "activity", zh: "活動(n)" },
  { id: 515, en: "sleepy", zh: "困乏的、欲睡的(adj)" },
  { id: 516, en: "frank", zh: "率直的、坦白的(adj)" },
  { id: 517, en: "international", zh: "國際的、世界(性)的(adj)" },
  { id: 518, en: "sneaky", zh: "鬼祟的、卑劣的(adj)" },
  { id: 519, en: "railroad", zh: "鐵路(n)" },
  { id: 520, en: "basis", zh: "基礎、基本、根據、主要成分(或要素)(認識論中的)基本原則或原理(n)" },
  { id: 521, en: "ink", zh: "墨水、油墨(n)" },
  { id: 522, en: "revise", zh: "修訂、校訂、修正(v)" },
  { id: 523, en: "basic", zh: "基本的、基礎的(adj)" },
  { id: 524, en: "beyond", zh: "在…那邊、遠於、超出、超過(prep) 在遠處(adv)" },
  { id: 525, en: "painful", zh: "疼痛的、辛苦的(adj)" },
  { id: 526, en: "limit", zh: "限度、限制(複)範圍(n) 限定、限制(vt)" },
  { id: 527, en: "temple", zh: "神殿、寺廟、教堂、殿堂(n)" },
  { id: 528, en: "usual", zh: "通常的、平常的(adj)" },
  { id: 529, en: "mat", zh: "席子(n)" },
  { id: 530, en: "alone", zh: "單獨的、孤獨的(adj) 單獨地、獨自地、僅僅、只(adv)" },
  { id: 531, en: "hippopotamus", zh: "河馬(n)" },
  { id: 532, en: "Canada", zh: "加拿大(n)" },
  { id: 533, en: "custom", zh: "風俗習慣(n)" },
  { id: 534, en: "offer", zh: "給予、提供、提出(vt) 提供物、提議(n)" },
  { id: 535, en: "visitor", zh: "參觀者、訪問者(n)" },
  { id: 536, en: "alley", zh: "弄、小巷、胡同(n)" },
  { id: 537, en: "traffic lights", zh: "紅綠燈、交通燈(n)" },
  { id: 538, en: "law", zh: "法律、法規、法則(n)" },
  { id: 539, en: "obey", zh: "順從、聽從(vt)" },
  { id: 540, en: "energy", zh: "精力、活力、能(量)(n)" },
  { id: 541, en: "computer game", zh: "電腦遊戲(n)" },
  { id: 542, en: "shower", zh: "陣雨、暴雨、淋浴(一)陣、大批(n)" },
  { id: 543, en: "shut", zh: "關(閉)(v)" },
  { id: 544, en: "gain", zh: "獲得、增加(vt) 受益、增加(vi)" },
  { id: 545, en: "dolphin", zh: "海豚(n)" },
  { id: 546, en: "potato", zh: "馬鈴薯(n)" },
  { id: 547, en: "desert", zh: "沙漠、不毛之地(n) 遺棄(vt)" },
  { id: 548, en: "table cloth", zh: "桌布(n)" },
  { id: 549, en: "score", zh: "得分、分數、二十(n) 得分、記分(vt)" },
  { id: 550, en: "insist", zh: "(on、 upon)堅持、堅決主張、堅決要求(vi) 堅持、堅決主張、堅決認為(vt)" },
  { id: 551, en: "mop", zh: "拖把(俗稱地拖) 洗碗(n) 用拖把拖洗、擦、抹、掃蕩(v)" },
  { id: 552, en: "traffic jam", zh: "交通阻塞(n)" },
  { id: 553, en: "bus stop", zh: "公共汽車站(n)" },
  { id: 554, en: "minus", zh: "減(prep)" },
  { id: 555, en: "recover", zh: "重新獲得、恢復(v)" },
  { id: 556, en: "nephew", zh: "侄子、外甥(n)" },
  { id: 557, en: "Taiwanese", zh: "台灣的、台灣人(a、 n)" },
  { id: 558, en: "haircut", zh: "理髮、剪髮的方式(n)" },
  { id: 559, en: "highway", zh: "公路(n)" },
  { id: 560, en: "toothbrush", zh: "牙刷(n)" },
  { id: 561, en: "bun", zh: "小圓麵包(n)" },
  { id: 562, en: "toothache", zh: "牙痛(n)" },
  { id: 563, en: "servant", zh: "僕人(n)" },
  { id: 564, en: "pleasure", zh: "高興、樂趣、喜悅(n)" },
  { id: 565, en: "wonder", zh: "感到驚訝、詫異(vi) 想知道(vt)" },
  { id: 566, en: "deep", zh: "深的、縱深的、深切的(adj) 深深地(adv)" },
  { id: 567, en: "extra", zh: "額外的、外加的(adj) 特別地(adv)" },
  { id: 568, en: "oven", zh: "烤爐、烤箱(n)" },
  { id: 569, en: "broad", zh: "寬的、闊的、廣闊的、廣泛的(adj)" },
  { id: 570, en: "measure", zh: "量、測量(vt) 有…長(或寬、高等)(vi)" },
  { id: 571, en: "imagine", zh: "料想、設想、想像(vt)" },
  { id: 572, en: "far", zh: "遠(adj)" },
  { id: 573, en: "nor", zh: "也不、也沒有(conj)" },
  { id: 574, en: "unique", zh: "唯一的、獨特的、獨一無二的(adj)" },
  { id: 575, en: "chief", zh: "首領、酋長(n) 首要的、主要的(adj)" },
  { id: 576, en: "skill", zh: "技能、技巧、手藝(n)" },
  { id: 577, en: "cheerleader", zh: "啦啦隊隊長(n)" },
  { id: 578, en: "address", zh: "地址、住址、演講(n) 寫姓名地址(於郵件上) 向…講話(vt)" },
  { id: 579, en: "division", zh: "分開、分割、區分、除法、公司(軍事)師、分配、分界線(n)" },
  { id: 580, en: "deer", zh: "鹿(n)" },
  { id: 581, en: "instrument", zh: "器械、器具、儀器、樂器(n)" },
  { id: 582, en: "necklace", zh: "項圈、項鍊(n)" },
  { id: 583, en: "avoid", zh: "避免(v)" },
  { id: 584, en: "golden", zh: "金(黃)色的、金(製)的、極好的(adj)" },
  { id: 585, en: "parrot", zh: "鸚鵡(n)" },
  { id: 586, en: "protect", zh: "保護、保衛(v)" },
  { id: 587, en: "trace", zh: "追蹤、跟蹤(vt) 痕跡、蹤跡(n)" },
  { id: 588, en: "hop", zh: "單腳跳、雙腳跳躍(v)" },
  { id: 589, en: "classical", zh: "古典的、模範的、傳統的(adj)" },
  { id: 590, en: "rare", zh: "稀有的、三分熟的(adj)" },
  { id: 591, en: "needle", zh: "針(n)" },
  { id: 592, en: "marry", zh: "結婚(vi) 娶、嫁、和…結婚(vt)" },
  { id: 593, en: "realize", zh: "實現、實行、認清、認識(v)" },
  { id: 594, en: "democratic", zh: "民主的、民主主義的、民主政體的、平民的(adj)" },
  { id: 595, en: "negative", zh: "負的、負面的(adj) 底片(n)" },
  { id: 596, en: "lunch box", zh: "午餐盒、飯盒(n)" },
  { id: 597, en: "gloves", zh: "手套(n)" },
  { id: 598, en: "instant", zh: "瞬間、時刻(n) 立即的、即刻的、緊急的(adj)" },
  { id: 599, en: "get on", zh: "上車(片)" },
  { id: 600, en: "advise", zh: "勸告、建議、通知(vt)" },
  { id: 601, en: "track", zh: "跑道、小路、軌道、足跡、蹤跡(n) 跟蹤、追蹤(vt)" },
  { id: 602, en: "climate", zh: "氣候、風土、潮流(n)" },
  { id: 603, en: "throughout", zh: "遍及、貫穿(prep) 到處、自始至終(adv)" },
  { id: 604, en: "skate", zh: "溜冰鞋、冰刀、輪鞋、輪式溜冰鞋(n)" },
  { id: 605, en: "raincoat", zh: "雨衣(n)" },
  { id: 606, en: "stationery", zh: "文具、信紙(n)" },
  { id: 607, en: "human", zh: "人的、人類的(adj) 人(n)" },
  { id: 608, en: "stingy", zh: "吝嗇的、小氣的(adj)" },
  { id: 609, en: "Frisbee", zh: "飛盤(n)" },
  { id: 610, en: "fence", zh: "柵欄、圍欄、籬笆(n)" },
  { id: 611, en: "examine", zh: "檢查、調查、考試(v)" },
  { id: 612, en: "sink", zh: "沉、沉沒、下陷(v)" },
  { id: 613, en: "shoot", zh: "嫩枝、苗(n)" },
  { id: 614, en: "fool", zh: "蠢人、傻瓜(n) 愚弄、欺騙(vt)" },
  { id: 615, en: "kangaroo", zh: "袋鼠(n)" },
  { id: 616, en: "bean", zh: "豆(n)" },
  { id: 617, en: "wheel", zh: "輪、車輪(n)" },
  { id: 618, en: "role", zh: "角色、作用、任務(n)" },
  { id: 619, en: "mosquito", zh: "蚊子(n)" },
  { id: 620, en: "talkative", zh: "多嘴的、饒舌的(adj)" },
  { id: 621, en: "certain", zh: "確定的、肯定的(adj)" },
  { id: 622, en: "rush", zh: "衝、奔、倉促行動(vi) 催促(vt)" },
  { id: 623, en: "wolf", zh: "狼(n)" },
  { id: 624, en: "gas station", zh: "加油站(n)" },
  { id: 625, en: "pronounce", zh: "發音、宣佈(vt)" },
  { id: 626, en: "pollute", zh: "弄髒、污染(v)" },
  { id: 627, en: "wild", zh: "野生的、未馴化的、荒蕪的、瘋狂的(adj)" },
  { id: 628, en: "jealous", zh: "妒忌的、羡慕的、猜忌的(adj)" },
  { id: 629, en: "dinosaur", zh: "恐龍(n)" },
  { id: 630, en: "toilet", zh: "浴室、廁所(n)" },
  { id: 631, en: "storm", zh: "暴風雨、暴風雪(n) 下暴雨、起風暴(vi)" },
  { id: 632, en: "countryside", zh: "農村(n)" },
  { id: 633, en: "Halloween", zh: "萬聖節前夕(月日)(n)" },
  { id: 634, en: "Mid-Autumn Festival", zh: "中秋節(n)" },
  { id: 635, en: "better", zh: "較好的、更好的(健康)好轉的(adj) 更好地(adv)" },
  { id: 636, en: "housework", zh: "家務勞動(n)" },
  { id: 637, en: "final", zh: "最後的、最終的、決定性的(adj)" },
  { id: 638, en: "elder", zh: "年齡大的、年長的(adj)(複)長輩(n)" },
  { id: 639, en: "rock", zh: "岩石、石塊、搖滾(音樂)(n) 搖(動)(vt)" },
  { id: 640, en: "primary", zh: "第一的、主要的(adj)" },
  { id: 641, en: "equal", zh: "相等的、同樣的、平等的(adj) 等於(vt)" },
  { id: 642, en: "wood", zh: "木材、木桶(n)" },
  { id: 643, en: "complete", zh: "完全的、完整的(adj) 完成、使…完整(vt)" },
  { id: 644, en: "opinion", zh: "意見、看法(n)" },
  { id: 645, en: "crowded", zh: "擁擠的、客滿的(adj)" },
  { id: 646, en: "sharp", zh: "鋒利的、銳利的、鮮明的、急劇的(adj)" },
  { id: 647, en: "suggest", zh: "建議、提議、暗示、表明(vt)" },
  { id: 648, en: "poison", zh: "毒(n)" },
  { id: 649, en: "member", zh: "成員、會員(n)" },
  { id: 650, en: "paste", zh: "糊狀物、麵團(n)" },
  { id: 651, en: "used", zh: "用過的、舊的(adj) 習慣於…的(adj)" },
  { id: 652, en: "lychee", zh: "荔枝(n)" },
  { id: 653, en: "brief", zh: "摘要、大綱(n) 簡短的、短暫的(adj)" },
  { id: 654, en: "silence", zh: "寂靜、沈默(n)" },
  { id: 655, en: "simply", zh: "簡單地、僅僅、只不過(adv)" },
  { id: 656, en: "goodness", zh: "善良、仁慈、親切(n)" },
  { id: 657, en: "emphasize", zh: "強調(v)" },
  { id: 658, en: "grape", zh: "葡萄(n)" },
  { id: 659, en: "express", zh: "表示、表達(vt) 快車、快遞(n)" },
  { id: 660, en: "attack", zh: "攻擊、進攻、襲擊(v)" },
  { id: 661, en: "hunter", zh: "獵人、打獵者(n)" },
  { id: 662, en: "pot", zh: "罐、壺(n)" },
  { id: 663, en: "pleasant", zh: "令人愉快的、討人喜歡的(adj)" },
  { id: 664, en: "tub", zh: "桶、盆、浴盆(n)" },
  { id: 665, en: "collection", zh: "收藏、徵收、搜集品、捐款(n)" },
  { id: 666, en: "charge", zh: "索價、控告、充電(vt) 費用、指控、充電(n)" },
  { id: 667, en: "pocket", zh: "衣袋、小袋、口袋(n) 袖珍的、小型的(adj)" },
  { id: 668, en: "power", zh: "權力、勢力、力(量) 功率、動力(n)" },
  { id: 669, en: "result", zh: "結果、成果、成績(n) 導致、結果是(in) 起因於(from)(vi)" },
  { id: 670, en: "cable", zh: "粗索、電纜、錨鏈(n)" },
  { id: 671, en: "local", zh: "本地的、局部的(adj)" },
  { id: 672, en: "abroad", zh: "國外、海外(adv)" },
  { id: 673, en: "meter", zh: "米、公尺(n)" },
  { id: 674, en: "available", zh: "可利用的、可獲取得的(adj)" },
  { id: 675, en: "volleyball", zh: "排球(n)" },
  { id: 676, en: "toe", zh: "腳趾、腳尖(n)" },
  { id: 677, en: "tent", zh: "帳蓬(n)" },
  { id: 678, en: "shock", zh: "震動、震驚、休克(n)(使)震動(使)震驚(v)" },
  { id: 679, en: "arrest", zh: "逮捕、拘留(vt)" },
  { id: 680, en: "divide", zh: "分、劃分(into) 隔開、除(by)(vt)" },
  { id: 681, en: "Chinese New Year", zh: "農曆新年(n)" },
  { id: 682, en: "British", zh: "不列顛(人)的、英國(人)的(adj) 英國人(n)" },
  { id: 683, en: "victory", zh: "勝利(n)" },
  { id: 684, en: "fever", zh: "發燒、一時的狂熱(n)" },
  { id: 685, en: "earrings", zh: "耳環、耳飾、耳墜(n)" },
  { id: 686, en: "tail", zh: "尾巴、後部(n)" },
  { id: 687, en: "flute", zh: "笛、長笛(n)" },
  { id: 688, en: "absent", zh: "缺席的、心不在焉的(adj)" },
  { id: 689, en: "yard", zh: "院子、場地(n)" },
  { id: 690, en: "saucer", zh: "碟子(n)" },
  { id: 691, en: "tour", zh: "旅行、遊歷(n) 旅行、遊歷(v)" },
  { id: 692, en: "transportation", zh: "運輸(n)" },
  { id: 693, en: "women's room", zh: "女廁所(n)" },
  { id: 694, en: "aircraft", zh: "飛行器、航行器(n)" },
  { id: 695, en: "confident", zh: "自信的(adj)" },
  { id: 696, en: "within", zh: "在…內(prep)" },
  { id: 697, en: "surf", zh: "海浪、拍岸浪(n) 在激浪上駕(船) 在…衝浪(vt)" },
  { id: 698, en: "favor", zh: "好感、喜愛、贊同、支援、恩惠、好事(n) 贊同、偏愛(vt)" },
  { id: 699, en: "gun", zh: "槍、手槍(n)" },
  { id: 700, en: "report", zh: "報告(書)(n)" },
  { id: 701, en: "humor", zh: "幽默、詼諧(n)" },
  { id: 702, en: "section", zh: "切斷、斷片、組件、區域(n)" },
  { id: 703, en: "race", zh: "比賽、種族(n) 全速前進、賽跑(v)" },
  { id: 704, en: "oh", zh: "噢、啊、唉(int)" },
  { id: 705, en: "rob", zh: "搶劫、剝奪(v)" },
  { id: 706, en: "cancel", zh: "取消(v)" },
  { id: 707, en: "hip", zh: "臀部(n)" },
  { id: 708, en: "education", zh: "教育、培養(n)" },
  { id: 709, en: "unfriendly", zh: "不友善地(adv)" },
  { id: 710, en: "Australian", zh: "澳大利亞(人)的(adj) 澳大利亞人(n)" },
  { id: 711, en: "swimming", zh: "游泳(n)" },
  { id: 712, en: "peaceful", zh: "和平的、平靜的、安寧的(adj)" },
  { id: 713, en: "alike", zh: "同樣的、相像的(adj)" },
  { id: 714, en: "burger", zh: "(口)漢堡(n)" },
  { id: 715, en: "president", zh: "總統、校長、會長、總裁、主席(n)" },
  { id: 716, en: "movie star", zh: "電影明星(n)" },
  { id: 717, en: "goal", zh: "球門、進球、得分、目標、目的(n)" },
  { id: 718, en: "compare", zh: "比較、對照(vt)" },
  { id: 719, en: "cockroach", zh: "蟑螂(n)" },
  { id: 720, en: "trust", zh: "信任、信賴、相信(n) 信任、信賴、相信(v)" },
  { id: 721, en: "dishonest", zh: "不誠實的、不正直的(adj)" },
  { id: 722, en: "beat", zh: "打、擊、打敗(vt)(心臟等)跳動(vi)" },
  { id: 723, en: "thirtieth", zh: "第三十(num) 三十分之一(n)" },
  { id: 724, en: "cream", zh: "奶油、膏、霜(n)" },
  { id: 725, en: "policeman", zh: "警察(n)" },
  { id: 726, en: "papaya", zh: "木瓜樹、木瓜(n)" },
  { id: 727, en: "search", zh: "搜、尋、探查(v) 搜、尋、探查(n)" },
  { id: 728, en: "building", zh: "建築物、大樓(n)" },
  { id: 729, en: "cage", zh: "籠(n)" },
  { id: 730, en: "fast food", zh: "速食(n)" },
  { id: 731, en: "minor", zh: "較小的、較少的、較次要的(adj)" },
  { id: 732, en: "grand", zh: "盛大的、豪華的、重大的、主要的、極重要的(adj)" },
  { id: 733, en: "contact lens", zh: "隱形眼鏡(n)" },
  { id: 734, en: "admire", zh: "欽佩、讚賞(vt)" },
  { id: 735, en: "toast", zh: "烤麵包片、土司(n)" },
  { id: 736, en: "rectangle", zh: "長方形(n)" },
  { id: 737, en: "necessary", zh: "必要的、必然的(adj)" },
  { id: 738, en: "traditional", zh: "傳統的、慣例的(adj)" },
  { id: 739, en: "either xxx or", zh: "或者…或者…" },
  { id: 740, en: "evil", zh: "壞的、邪惡的(adj)" },
  { id: 741, en: "last name", zh: "姓(n)" },
  { id: 742, en: "crisis", zh: "危機、危急關頭(n)" },
  { id: 743, en: "punish", zh: "懲罰、處罰(vt)" },
  { id: 744, en: "sample", zh: "樣品、標本(n) 從…抽樣(vt)" },
  { id: 745, en: "introduce", zh: "介紹、引進、傳入(vt)" },
  { id: 746, en: "fried rice", zh: "炒飯(n)" },
  { id: 747, en: "nut", zh: "堅果(如核桃、栗子等)(n)" },
  { id: 748, en: "artist", zh: "藝術家、美術家(n)" },
  { id: 749, en: "principal", zh: "校長(n)" },
  { id: 750, en: "universe", zh: "宇宙(n)" },
  { id: 751, en: "kilometer", zh: "公里、千米(n)" },
  { id: 752, en: "edge", zh: "邊、邊緣、棱(n)" },
  { id: 753, en: "whole", zh: "全部的、整體的(adj) 全部、整體(n)" },
  { id: 754, en: "stream", zh: "小河、溪、流動、潮流(n)" },
  { id: 755, en: "semester", zh: "學期、半學年(n)" },
  { id: 756, en: "silver", zh: "銀色的(adj) 銀色(n)" },
  { id: 757, en: "seed", zh: "種子(n)" },
  { id: 758, en: "location", zh: "場所、位置、地點(n)" },
  { id: 759, en: "first name", zh: "名(n)" },
  { id: 760, en: "while", zh: "在(當)…的時候、和…同時(conj)" },
  { id: 761, en: "allow", zh: "允許、准許(vt)" },
  { id: 762, en: "clever", zh: "聰明的、機靈的(adj)" },
  { id: 763, en: "personal", zh: "個人的、私人的、本人的、親自的(adj)" },
  { id: 764, en: "oh-oh", zh: "哦哦(interj)" },
  { id: 765, en: "general", zh: "一般的、通用的(adj) 將軍(n)" },
  { id: 766, en: "envelope", zh: "信封(n)" },
  { id: 767, en: "printer", zh: "印表機(n)" },
  { id: 768, en: "vote", zh: "投票(v)" },
  { id: 769, en: "Mandarin", zh: "標準中國話(n)" },
  { id: 770, en: "get off", zh: "下車、從…下來(片)" },
  { id: 771, en: "besides", zh: "在…旁邊、在…附近(prep)" },
  { id: 772, en: "blood", zh: "血(液) 血統(n)" },
  { id: 773, en: "shake", zh: "握手(v)" },
  { id: 774, en: "fight", zh: "作戰、戰鬥、交戰;打架;搏鬥、格鬥;拳擊比賽(n) 戰鬥、作戰、鬥爭、爭鬥;搏鬥、打架(vi)" },
  { id: 775, en: "tank", zh: "槽、戰車、坦克車(n)" },
  { id: 776, en: "model", zh: "模型、模範、模特兒(汽車、機器)型號(n)" },
  { id: 777, en: "type", zh: "類型、種類、品種(n) 打字(v)" },
  { id: 778, en: "second grade", zh: "二年級(n)" },
  { id: 779, en: "industry", zh: "工業、產業、行業、勤奮(n)" },
  { id: 780, en: "Youth Day", zh: "青年節(n)" },
  { id: 781, en: "nature", zh: "大自然、性質(n)" },
  { id: 782, en: "across", zh: "橫過、穿過、在…對面(prep) 橫過、穿過、…寬(adv)" },
  { id: 783, en: "direct", zh: "直接的(adj) 指示、導演、管理(vt)" },
  { id: 784, en: "sudden", zh: "突然的、意外的(adj)" },
  { id: 785, en: "invitation", zh: "邀請(n)" },
  { id: 786, en: "donkey", zh: "驢子、傻瓜(n)" },
  { id: 787, en: "sand", zh: "沙(複)沙灘(n)" },
  { id: 788, en: "connective", zh: "連結的、連接的(adj) 連結詞(n)" },
  { id: 789, en: "expect", zh: "預料、等待、期待(vt)" },
  { id: 790, en: "pale", zh: "蒼白的、灰白的、淡的(adj)" },
  { id: 791, en: "prove", zh: "證明、證實(vt) 結果是、果然是(vi)" },
  { id: 792, en: "flashlight", zh: "手電筒、閃光、閃光信號燈(n)" },
  { id: 793, en: "actress", zh: "女演員(n)" },
  { id: 794, en: "soldier", zh: "士兵、軍人(n)" },
  { id: 795, en: "both xxx and", zh: "兩個都…、既…又…" },
  { id: 796, en: "bookcase", zh: "書櫥(n)" },
  { id: 797, en: "submarine", zh: "潛艇(n)" },
  { id: 798, en: "chase", zh: "追趕、驅逐、追求、追捕(v)" },
  { id: 799, en: "review", zh: "評論、回顧、復習(n) 審查、復習、評論(vt)" },
  { id: 800, en: "anger", zh: "憤怒(n) 使發怒(vt)" },
  { id: 801, en: "Englishman", zh: "英格蘭人、英國人(n)" },
  { id: 802, en: "county", zh: "縣、郡(n)" },
  { id: 803, en: "spider", zh: "蜘蛛、三腳架(n)" },
  { id: 804, en: "fried chicken", zh: "炸雞(n)" },
  { id: 805, en: "San Francisco", zh: "舊金山(n)" },
  { id: 806, en: "cabbage", zh: "甘藍菜、捲心菜(n)" },
  { id: 807, en: "therefore", zh: "因此、所以(adv)" },
  { id: 808, en: "purse", zh: "錢包(n)" },
  { id: 809, en: "ski", zh: "滑雪板、雪屐、雪橇(n) 滑雪(v)" },
  { id: 810, en: "tummy", zh: "(兒語)肚子(n)" },
  { id: 811, en: "private", zh: "私人的、個人的(adj)" },
  { id: 812, en: "twelfth", zh: "第十二(num) 十二分之一(n)" },
  { id: 813, en: "style", zh: "作風、風格、樣式(n)" },
  { id: 814, en: "title", zh: "標題、頭銜(n)" },
  { id: 815, en: "determine", zh: "決定、決心(vt)" },
  { id: 816, en: "jeep", zh: "吉普車(n)" },
  { id: 817, en: "addition", zh: "加、加起來、增加物、增加、加法(n)" },
  { id: 818, en: "downtown", zh: "往市中心、在市中心(adv) 往市中心、在市中心(adj)" },
  { id: 819, en: "angel", zh: "天使、完善可愛的人(n)" },
  { id: 820, en: "bug", zh: "蟲、軟體錯誤(n)" },
  { id: 821, en: "snowy", zh: "下雪的(adj)" },
  { id: 822, en: "doubt", zh: "懷疑(n)" },
  { id: 823, en: "steal", zh: "偷、竊取(v)" },
  { id: 824, en: "period", zh: "(一段)時間、時期、句號、句點(n)" },
  { id: 825, en: "painter", zh: "畫家、油漆匠(n)" },
  { id: 826, en: "guide", zh: "嚮導、導遊、指南(n) 給…領路、指導(vt)" },
  { id: 827, en: "joke", zh: "笑話、玩笑(n) 說笑話、開玩笑(vi)" },
  { id: 828, en: "branch", zh: "樹枝、分支、分部、分公司(n)" },
  { id: 829, en: "alarm clock", zh: "鬧鐘(n)" },
  { id: 830, en: "director", zh: "指導者、主任、董事、導演(n)" },
  { id: 831, en: "through", zh: "穿過、通過、以、用、憑藉、經由、從頭到尾(prep) 從頭到尾、徹底(adv)" },
  { id: 832, en: "dessert", zh: "甜點(n)" },
  { id: 833, en: "length", zh: "長度、距離、一段、一節(n)" },
  { id: 834, en: "depend", zh: "依靠、依賴、決定於(on、upon)(vi)" },
  { id: 835, en: "textbook", zh: "教科書、課本(n)" },
  { id: 836, en: "provide", zh: "供給、提供(vt)" },
  { id: 837, en: "fourteenth", zh: "第十四、十四分之一(n)" },
  { id: 838, en: "gym", zh: "體操房(n)" },
  { id: 839, en: "stamp", zh: "郵票、印花、印、圖章(n) 在…上蓋印(或郵戳)(vt)" },
  { id: 840, en: "magician", zh: "魔法師、術士、魔術師(n)" },
  { id: 841, en: "choose", zh: "選擇、挑選(vt)" },
  { id: 842, en: "project", zh: "專案、項目(n)" },
  { id: 843, en: "ant", zh: "螞蟻(n)" },
  { id: 844, en: "hunt", zh: "狩獵、獵取、追獵(v)" },
  { id: 845, en: "deal", zh: "給予、分配(vt) 交易、處理(with)(vi)(pt:dealt、pp:dealt)" },
  { id: 846, en: "frog", zh: "青蛙(n)" },
  { id: 847, en: "delay", zh: "推遲、耽擱(n)" },
  { id: 848, en: "Korea", zh: "韓國、朝鮮(n)" },
  { id: 849, en: "glasses", zh: "眼鏡(n)" },
  { id: 850, en: "link", zh: "(鏈)環、連結、連接(n) 連結、連接(v)" },
  { id: 851, en: "desire", zh: "願望、渴望(n) 想望、渴望(vt)" },
  { id: 852, en: "value", zh: "價值、價格、重要性(複)價值觀(n) 尊重、重視、評價(vt)" },
  { id: 853, en: "lack", zh: "缺乏、不足(n)" },
  { id: 854, en: "secret", zh: "秘密的、機密的(adj) 秘密、秘訣(n)" },
  { id: 855, en: "comb", zh: "梳子(n) 梳理(vt)" },
  { id: 856, en: "sailing", zh: "航行、出航(n)" },
  { id: 857, en: "underwear", zh: "內衣(n)" },
  { id: 858, en: "geographical", zh: "地理(學)的(adj)" },
  { id: 859, en: "treat", zh: "對待、處理、醫療、醫治、款待、招待(vt) 款待、請客(n)" },
  { id: 860, en: "choice", zh: "選擇、抉擇(n)" },
  { id: 861, en: "satisfied", zh: "滿意的(adj)" },
  { id: 862, en: "freezing", zh: "結冰的、極冷的(adj)" },
  { id: 863, en: "underpass", zh: "地道、地下道(n)" },
  { id: 864, en: "Australia", zh: "澳大利亞(n)" },
  { id: 865, en: "worth", zh: "值得(prep)" },
  { id: 866, en: "audience", zh: "聽眾、觀眾、接見、拜見(n)" },
  { id: 867, en: "nervous", zh: "神經緊張的、情緒不安的(adj)" },
  { id: 868, en: "loaf", zh: "一條(塊)麵包、麵包形食物(n)" },
  { id: 869, en: "ninetieth", zh: "第九十、九十分之一(n)" },
  { id: 870, en: "current", zh: "水流、電流(n) 當前的、流行的(adj)" },
  { id: 871, en: "ambulance", zh: "救護車(n)" },
  { id: 872, en: "puzzle", zh: "(使)迷惑(使)為難(v) 智力問題、智力遊戲、難題、令人費解的事(n)" },
  { id: 873, en: "bench", zh: "長凳、長椅(n)" },
  { id: 874, en: "natural", zh: "自然的、天然的(adj)" },
  { id: 875, en: "brave", zh: "勇敢的(adj)" },
  { id: 876, en: "achieve", zh: "完成、達到、實現(vt)" },
  { id: 877, en: "jogging", zh: "慢跑(n)" },
  { id: 878, en: "diplomat", zh: "外交官、有外交手腕的人、有權謀的人(n)" },
  { id: 879, en: "foolish", zh: "愚蠢的(adj)" },
  { id: 880, en: "field", zh: "田地、田野、領域、範圍(n)" },
  { id: 881, en: "castle", zh: "城堡(n)" },
  { id: 882, en: "character", zh: "性格、特性、特質、品格、人物(n)" },
  { id: 883, en: "treasure", zh: "財寶、寶藏(n)" },
  { id: 884, en: "height", zh: "高、高度、身高、頂點(複)高處、高地(n)" },
  { id: 885, en: "naughty", zh: "調皮的(adj)" },
  { id: 886, en: "get in", zh: "進入、坐上、搭乘(片)" },
  { id: 887, en: "armchair", zh: "扶手椅(n)" },
  { id: 888, en: "butterfly", zh: "蝴蝶(n)" },
  { id: 889, en: "zero", zh: "零(num) 零點、零度(n)" },
  { id: 890, en: "frighten", zh: "使…驚恐、嚇唬(vt)" },
  { id: 891, en: "geography", zh: "地理(學)(n)" },
  { id: 892, en: "stage", zh: "階段、時期、舞臺(n)" },
  { id: 893, en: "recycle", zh: "使再迴圈、反復應用(v) 再迴圈、再生、重復利用(n)" },
  { id: 894, en: "gather", zh: "聚集、集合(vi) 收集、採集(vt)" },
  { id: 895, en: "waterfall", zh: "瀑布(n)" },
  { id: 896, en: "emotion", zh: "情感、情緒、感情(n)" },
  { id: 897, en: "cell", zh: "單元、細胞、蜂房(尤指監獄或寺院的)單人房間、電池(n)" },
  { id: 898, en: "curve", zh: "曲線(n)" },
  { id: 899, en: "manner", zh: "禮貌(n)" },
  { id: 900, en: "aid", zh: "幫助、援助、幫助者、有幫助的事物(n) 資助、援助、幫助(vt)" },
  { id: 901, en: "lay", zh: "放、置、產(卵) 打倒(v)" },
  { id: 902, en: "helicopter", zh: "直升飛機(n)" },
  { id: 903, en: "first grade", zh: "一年級(n)" },
  { id: 904, en: "ill", zh: "有病的、壞的(adj) 壞、不利地(adv)" },
  { id: 905, en: "mall", zh: "散步式商店街、林蔭路、步行街道(n)" },
  { id: 906, en: "French fries", zh: "炸薯條(n)" },
  { id: 907, en: "dawn", zh: "黎明、開始(n) 破曉、開始發展(vi)" },
  { id: 908, en: "tool", zh: "工具(n)" },
  { id: 909, en: "tradition", zh: "傳統、慣例(n)" },
  { id: 910, en: "thick", zh: "厚的、粗的、稠的、濃的(adj)" },
  { id: 911, en: "mirror", zh: "鏡子(n)" },
  { id: 912, en: "cruel", zh: "殘酷的、殘忍的(adj)" },
  { id: 913, en: "burst", zh: "爆裂(v) 爆炸、爆裂(n)" },
  { id: 914, en: "fox", zh: "狐狸、狡猾的人(n)" },
  { id: 915, en: "aim", zh: "把…瞄準、把…對準(vt) 瞄準、旨在(at)(vi)" },
  { id: 916, en: "temperature", zh: "溫度(n)" },
  { id: 917, en: "youth", zh: "青春、青少年時期、小夥子(總稱)年輕人(n)" },
  { id: 918, en: "seventeenth", zh: "第十七、十七分之一(n)" },
  { id: 919, en: "beginner", zh: "初學者(n)" },
  { id: 920, en: "manager", zh: "管理者、經營者、處理者(vt)" },
  { id: 921, en: "Japanese", zh: "日本(人)的、日語的(adj) 日本人、日語(n)" },
  { id: 922, en: "village", zh: "村莊、鄉村(n)" },
  { id: 923, en: "advertisement", zh: "廣告、做廣告(n)" },
  { id: 924, en: "contract", zh: "合同、契約(n) 訂合同、縮小(vi)" },
  { id: 925, en: "college", zh: "大學、學院(n)" },
  { id: 926, en: "meaning", zh: "意義、意思(n)" },
  { id: 927, en: "major", zh: "較大的、主要的(adj) 專業(n)" },
  { id: 928, en: "false", zh: "假的(adj)" },
  { id: 929, en: "pear", zh: "梨(n)" },
  { id: 930, en: "blank", zh: "空的、空白的(adj)" },
  { id: 931, en: "serve", zh: "為…服務/盡責、招待、符合(v) 服務、供職、服役、起作用(as)(vi)" },
  { id: 932, en: "hall", zh: "大廳、禮堂、會堂(n)" },
  { id: 933, en: "necktie", zh: "領帶(n)" },
  { id: 934, en: "suit", zh: "合適、適合、中…的意(vt) 一套衣服(或西服) 起訴、訴訟(n)" },
  { id: 935, en: "method", zh: "方法、辦法(n)" },
  { id: 936, en: "bone", zh: "骨、骨骼(n)" },
  { id: 937, en: "hanger", zh: "掛衣架(n)" },
  { id: 938, en: "quickly", zh: "快、迅速地(adv)" },
  { id: 939, en: "product", zh: "產品(n)" },
  { id: 940, en: "classic", zh: "傑作、名著(n) 第一流的(adj)" },
  { id: 941, en: "cooking", zh: "烹調(n) 烹調用的(adj)" },
  { id: 942, en: "slippers", zh: "拖鞋(n)" },
  { id: 943, en: "Paris", zh: "巴黎(n)" },
  { id: 944, en: "gesture", zh: "(表達情意的)姿勢、手勢(n)" },
  { id: 945, en: "cancer", zh: "癌(n)" },
  { id: 946, en: "shark", zh: "鯊魚(n)" },
  { id: 947, en: "sign", zh: "標記、符號、招牌、徵兆、現象(n) 簽(名) 簽署(v)" },
  { id: 948, en: "brain", zh: "腦(袋) 智力(n)" },
  { id: 949, en: "eleventh", zh: "第十一(num) 十一分之一(n)" },
  { id: 950, en: "culture center", zh: "文化中心(n)" },
  { id: 951, en: "train station", zh: "火車站(n)" },
  { id: 952, en: "adopt", zh: "收養、採取(vt)" },
  { id: 953, en: "comment", zh: "註釋、註解、說明(n) 評論(v)" },
  { id: 954, en: "newspaper", zh: "報紙(n)" },
  { id: 955, en: "whom", zh: "(who的受格)誰(pron)" },
  { id: 956, en: "hang", zh: "懸掛、吊(v)(pt&pp:hung) 吊死、絞死(v)(pt&pp: hanged)" },
  { id: 957, en: "discussion", zh: "討論、談論(n)" },
  { id: 958, en: "T-shirt T", zh: "恤(n)" },
  { id: 959, en: "Thanksgiving Day", zh: "感恩節(n)" },
  { id: 960, en: "direction", zh: "方向、方位(複)使用說明(n)" },
  { id: 961, en: "wing", zh: "翅膀(n)" },
  { id: 962, en: "dizzy", zh: "暈眩的、眼花撩亂的(adj)" },
  { id: 963, en: "sailor", zh: "水手(n)" },
  { id: 964, en: "Singapore", zh: "新加坡(n)" },
  { id: 965, en: "master", zh: "主人、雇主、大師、能手、[M-]碩士(n) 精通(vt)" },
  { id: 966, en: "sail", zh: "帆、航行(n) 航行(vi)" },
  { id: 967, en: "pattern", zh: "型、模式、樣式、花樣、圖案(n)" },
  { id: 968, en: "valuable", zh: "貴重的、有價值的(adj) 貴重物品(n)" },
  { id: 969, en: "measurement", zh: "測量(n)" },
  { id: 970, en: "perfect", zh: "完美的、完滿的(語法)完成的(adj) 使…完美(vt)" },
  { id: 971, en: "boyfriend", zh: "男朋友(n)" },
  { id: 972, en: "quality", zh: "品質、特徵(n)" },
  { id: 973, en: "lettuce", zh: "萵苣(n)" },
  { id: 974, en: "debate", zh: "辯論、爭論(n)" },
  { id: 975, en: "calendar", zh: "月曆、行事曆(n)" },
  { id: 976, en: "spaghetti", zh: "義大利麵條(n)" },
  { id: 977, en: "importance", zh: "重要、重要性(n)" },
  { id: 978, en: "social", zh: "社交的、社會的(adj)" },
  { id: 979, en: "slim", zh: "苗條的、纖細的、修長的(adj)" },
  { id: 980, en: "barber", zh: "理髮師(n)" },
  { id: 981, en: "lawyer", zh: "律師(n)" },
  { id: 982, en: "plain", zh: "平原(n) 樸素的、簡單的、平常的(adj)" },
  { id: 983, en: "inch", zh: "英寸(n)" },
  { id: 984, en: "out of", zh: "出於…、向…外(片)" },
  { id: 985, en: "employ", zh: "雇用、使用(vt)" },
  { id: 986, en: "New Year's Day", zh: "新年元旦(n)" },
  { id: 987, en: "boil", zh: "沸騰(vi) 使…沸騰(vt)" },
  { id: 988, en: "sight", zh: "視力、視覺、望見、情景(複)風景(n)" },
  { id: 989, en: "support", zh: "支援、擁護、供養、支撐、維持(vt) 支援、支承、支撐(n)" },
  { id: 990, en: "such", zh: "這樣的、這種的(adj) 那麼(adv)" },
  { id: 991, en: "blame", zh: "責備、責怪、把…歸咎於(vt)(過錯、事故等的)責任、責怪、責備(n)" },
  { id: 992, en: "fog", zh: "霧(n) 霧(v)" },
  { id: 993, en: "article", zh: "文章、論文、條款、物件、[語法]冠詞(n)" },
  { id: 994, en: "straw", zh: "稻草、麥桿、吸管(n)" },
  { id: 995, en: "pillow", zh: "枕頭(n)" },
  { id: 996, en: "zebra", zh: "斑馬(n)" },
  { id: 997, en: "mix", zh: "(使…)混合、混淆(vt) 相混合(vi)" },
  { id: 998, en: "certainly", zh: "的確、一定、當然可以(adv)" },
  { id: 999, en: "campus", zh: "校園、園區(n)" },
  { id: 1000, en: "Taipei", zh: "台北(n)" },
  { id: 1001, en: "Tainan", zh: "台南(n)" },
  { id: 1002, en: "positive", zh: "確信的、正面的、積極的(adj)" },
  { id: 1003, en: "robot", zh: "機器人(n)" },
  { id: 1004, en: "central", zh: "中央的、中心的(adj)" },
  { id: 1005, en: "good looking", zh: "美貌的、漂亮的、英俊的(adj)" },
  { id: 1006, en: "pool", zh: "水池、共用物(n)" },
  { id: 1007, en: "surfing", zh: "衝浪、上網(n)" },
  { id: 1008, en: "cough", zh: "咳嗽(v) 咳嗽(n)" },
  { id: 1009, en: "omit", zh: "省略、刪節、遺漏(vt)" },
  { id: 1010, en: "top", zh: "頂(端) 上部(n) 最高的(adj)" },
  { id: 1011, en: "path", zh: "小路、小徑(n)" },
  { id: 1012, en: "AIDS", zh: "愛滋病(n)" },
  { id: 1013, en: "convenience store", zh: "便利商店(n)" },
  { id: 1014, en: "hunger", zh: "饑餓、渴望(for)(n)" },
  { id: 1015, en: "none", zh: "沒有一人(或物) 沒有一點兒(pron) 毫不、毫無(adv)" },
  { id: 1016, en: "asleep", zh: "睡覺的(adj)" },
  { id: 1017, en: "running nose", zh: "流鼻水(n)" },
  { id: 1018, en: "running", zh: "奔跑的、流動的(adj)" },
  { id: 1019, en: "occupation", zh: "職業、佔有、居住、佔領(n)" },
  { id: 1020, en: "sport", zh: "(體育)運動;(複)運動會(n)" },
  { id: 1021, en: "throw", zh: "扔(v)" },
  { id: 1022, en: "invite", zh: "邀請、聘請(vt)" },
  { id: 1023, en: "fair", zh: "公平的、公正的、尚可的(adj) 公平地(adv)" },
  { id: 1024, en: "chess", zh: "西洋棋(n)" },
  { id: 1025, en: "tableware", zh: "餐具(n)" },
  { id: 1026, en: "blouse", zh: "女式襯衫(n)" },
  { id: 1027, en: "New York", zh: "紐約(n)" },
  { id: 1028, en: "appreciate", zh: "瞭解、欣賞、感激、升值(v)" },
  { id: 1029, en: "nail", zh: "釘子、指甲(n) 釘、釘牢(vt)" },
  { id: 1030, en: "Russian", zh: "俄羅斯(人)的、俄語的(adj) 俄羅斯人、俄語(n)" },
  { id: 1031, en: "Easter", zh: "(基督)復活節(n)" },
  { id: 1032, en: "homesick", zh: "想家的、害思鄉病的(adj)" },
  { id: 1033, en: "operation", zh: "運轉、運行、動手術、經營、操作(n)" },
  { id: 1034, en: "snowman", zh: "雪人(n)" },
  { id: 1035, en: "indefinite", zh: "不確定的、不明確、無限期的(adj)" },
  { id: 1036, en: "terrific", zh: "令人恐怖的(adj)" },
  { id: 1037, en: "remind", zh: "提醒、使…想起(vt)" },
  { id: 1038, en: "fifteenth", zh: "第十五、十五分之一(n)" },
  { id: 1039, en: "spread", zh: "推開、塗敷、傳播(vt) 傳開、蔓延(vi)" },
  { id: 1040, en: "ceiling", zh: "天花板(n)" },
  { id: 1041, en: "crab", zh: "蟹、挑剔者(n)" },
  { id: 1042, en: "host", zh: "(款待客人的)主人、東道主(n)" },
  { id: 1043, en: "kitty", zh: "(兒語)小貓(n)" },
  { id: 1044, en: "crayon", zh: "有色粉筆、蠟筆、粉筆畫(n)" },
  { id: 1045, en: "pin", zh: "大頭針、別針(n) 別住、釘住(vt)" },
  { id: 1046, en: "granddaughter", zh: "孫女、外孫女(n)" },
  { id: 1047, en: "table tennis", zh: "乒乓球、桌球(n)" },
  { id: 1048, en: "northern", zh: "北方的、北部的(adj)" },
  { id: 1049, en: "stone", zh: "石頭、寶石(n)" },
  { id: 1050, en: "beautifully", zh: "美麗地(adv)" },
  { id: 1051, en: "wine", zh: "(葡萄)酒(n)" },
  { id: 1052, en: "enemy", zh: "敵人、敵軍、仇敵(n)" },
  { id: 1053, en: "huge", zh: "巨大的、龐大的(adj)" },
  { id: 1054, en: "jar", zh: "甕、瓶、罐(n)" },
  { id: 1055, en: "responsible", zh: "有責任的、應負責任的(adj)" },
  { id: 1056, en: "vest", zh: "背心(n)" },
  { id: 1057, en: "flat", zh: "平的、平坦的(adj) 公寓(n)" },
  { id: 1058, en: "monster", zh: "怪物、妖怪(n)" },
  { id: 1059, en: "France", zh: "法國(n)" },
  { id: 1060, en: "flour", zh: "麵粉(n)" },
  { id: 1061, en: "sheet", zh: "(一)張、片、薄片、床單(n)" },
  { id: 1062, en: "KTV", zh: "卡拉OK電視節目(n)" },
  { id: 1063, en: "hole", zh: "洞、孔、眼(n)" },
  { id: 1064, en: "panda", zh: "熊貓(n)" },
  { id: 1065, en: "pause", zh: "暫停、中止(vi)" },
  { id: 1066, en: "climbing", zh: "攀登、登山(n)" },
  { id: 1067, en: "quit", zh: "停止、放棄、辭(職)(v)" },
  { id: 1068, en: "sweep", zh: "(打)掃、掠過、掃視(v)" },
  { id: 1069, en: "hen", zh: "母雞(n)" },
  { id: 1070, en: "impolite", zh: "無禮的、沒規矩的(adj)" },
  { id: 1071, en: "gate", zh: "大門、柵門、登機門(n)" },
  { id: 1072, en: "Double Tenth Day", zh: "雙十節(n)" },
  { id: 1073, en: "pumpkin", zh: "南瓜(n)" },
  { id: 1074, en: "waist", zh: "腰、腰部(n)" },
  { id: 1075, en: "nineteenth", zh: "第十九、十九分之一(n)" },
  { id: 1076, en: "envy", zh: "羡慕、妒忌(v)" },
  { id: 1077, en: "whale", zh: "鯨魚(n)" },
  { id: 1078, en: "sixteenth", zh: "第十六、十六分之一(n)" },
  { id: 1079, en: "thanksgiving", zh: "感謝、[宗]感恩祈禱(n)" },
  { id: 1080, en: "speaker", zh: "說話者、演講者、揚聲器(n)" },
  { id: 1081, en: "dial", zh: "(電話的)撥號盤、刻度盤(n)" },
  { id: 1082, en: "steam", zh: "(蒸)汽(n) 冒蒸汽(vi)" },
  { id: 1083, en: "grow up", zh: "長大(片)" },
  { id: 1084, en: "childish", zh: "孩子氣的、幼稚的、傻氣的(adj)" },
  { id: 1085, en: "successfully", zh: "成功地(adv)" },
  { id: 1086, en: "thirteenth", zh: "第十三、十三分之一(n)" },
  { id: 1087, en: "family name", zh: "姓(n)" },
  { id: 1088, en: "crowd", zh: "群、人群、群眾(n) 聚集、群集(vi)" },
  { id: 1089, en: "Korean", zh: "韓國(人、語)的、朝鮮(人、語)的(adj、 n)" },
  { id: 1090, en: "command", zh: "命令、指揮(vt) 命令、控制(n)" },
  { id: 1091, en: "wooden", zh: "木製的(adj)" },
  { id: 1092, en: "handle", zh: "柄、把手(n) 拿、操作、處理(vt)" },
  { id: 1093, en: "ancient", zh: "已往的、古代的、遠古的、舊式的(adj)" },
  { id: 1094, en: "unit", zh: "個體(計量)單位(軍隊的)部隊單位、[數學]最小的整數(n)" },
  { id: 1095, en: "beer", zh: "啤酒(n)" },
  { id: 1096, en: "cereal", zh: "穀物、穀類食品(麥片等)(n)" },
  { id: 1097, en: "shorts", zh: "短褲(n)" },
  { id: 1098, en: "duck", zh: "鴨子(n)" },
  { id: 1099, en: "port", zh: "港口(n)" },
  { id: 1100, en: "MTV", zh: "音樂電視 Music TV(n)" },
  { id: 1101, en: "survive", zh: "活下來、倖存(vi) 從…中逃出、從(因環境中)挺過來(vt)" },
  { id: 1102, en: "confirm", zh: "證實、確實、確切(vt)" },
  { id: 1103, en: "suitcase", zh: "衣箱、小提箱(n)" },
  { id: 1104, en: "diamond", zh: "鑽石、金剛石、菱形(n)" },
  { id: 1105, en: "lift", zh: "提、帶(v) 電梯、上升(力) 免費搭車(n)" },
  { id: 1106, en: "secretary", zh: "秘書、書記、大臣(n)" },
  { id: 1107, en: "primary school", zh: "小學(n)" },
  { id: 1108, en: "whatever", zh: "無論什麼、不管什麼(pron) 不管怎樣的、無論什麼樣的(adj)" },
  { id: 1109, en: "MRT", zh: "大眾捷運系統 Mass Rapid Transit(n)" },
  { id: 1110, en: "difference", zh: "差別、差異、差額(n)" },
  { id: 1111, en: "select", zh: "挑選、選擇(v)" },
  { id: 1112, en: "German", zh: "德國(人)的、德語的(adj) 德國人、德語(n)" },
  { id: 1113, en: "jam", zh: "果醬、堵塞(n) 堵塞、卡住(v)" },
  { id: 1114, en: "male", zh: "雄的(n)" },
  { id: 1115, en: "among", zh: "在…之中、在…之間(prep)" },
  { id: 1116, en: "dragon", zh: "龍(n)" },
  { id: 1117, en: "course", zh: "課程、教程、進程、路線(一)道(菜)(n)" },
  { id: 1118, en: "bother", zh: "打擾、麻煩(v) 麻煩、打擾(n)" },
  { id: 1119, en: "prefer", zh: "更喜歡、寧願(vt)" },
  { id: 1120, en: "claim", zh: "聲稱、主張、要求(vt) 要求、主張、斷言(n)" },
  { id: 1121, en: "vocabulary", zh: "字彙、生字(n)" },
  { id: 1122, en: "detect", zh: "發覺、識破、查出(v)" },
  { id: 1123, en: "girlfriend", zh: "女朋友(n)" },
  { id: 1124, en: "mango", zh: "芒果(n)" },
  { id: 1125, en: "silly", zh: "傻的、糊塗的(adj)" },
  { id: 1126, en: "adult", zh: "成人(n)" },
  { id: 1127, en: "loser", zh: "損失者、失敗者、前科犯(n)" },
  { id: 1128, en: "preposition", zh: "介系詞、前置詞(n)" },
  { id: 1129, en: "base", zh: "基地(n) 建立在…基礎上(vt)" },
  { id: 1130, en: "struggle", zh: "鬥爭、奮鬥、努力、掙扎(n) 鬥爭、奮鬥、努力、掙扎(vi)" },
  { id: 1131, en: "sense", zh: "感言、官能、感覺、意義、判斷力(n) 覺得、意識到(vt)" },
  { id: 1132, en: "repair", zh: "修理、修補(n) 修理、修補(vt)" },
  { id: 1133, en: "walkman", zh: "隨身聽(n)" },
  { id: 1134, en: "Asian", zh: "亞洲(人)的(adj) 亞洲人(n)" },
  { id: 1135, en: "plus", zh: "加(prep)" },
  { id: 1136, en: "shrimp", zh: "小蝦、矮個子、無名小卒(n)" },
  { id: 1137, en: "fire station", zh: "消防站(n)" },
  { id: 1138, en: "accident", zh: "意外的事、事故(n)" },
  { id: 1139, en: "ma'am", zh: "(對女主人、女教師等的稱呼)太太、小姐(n)" },
  { id: 1140, en: "complain", zh: "抱怨(v)" },
  { id: 1141, en: "against", zh: "違反、逆、反(對) 倚在、緊靠在(prep)" },
  { id: 1142, en: "reading", zh: "閱讀、朗讀(n)" },
  { id: 1143, en: "missing", zh: "失去的、不見了的(adj)" },
  { id: 1144, en: "drum", zh: "鼓(n)" },
  { id: 1145, en: "entire", zh: "全部的、整個的(adj)" },
  { id: 1146, en: "pan", zh: "平底鍋(n)" },
  { id: 1147, en: "journalist", zh: "新聞工作者、記者(n)" },
  { id: 1148, en: "diary", zh: "日記、日記本(n)" },
  { id: 1149, en: "extra large", zh: "特大號的(adj)" },
  { id: 1150, en: "court", zh: "庭院、場地、法庭、法院(n)" },
  { id: 1151, en: "pleased", zh: "滿意的(adj)" },
  { id: 1152, en: "quarter", zh: "四分之一、季度、一刻鐘(n)" },
  { id: 1153, en: "parking lot", zh: "停車場(n)" },
  { id: 1154, en: "fear", zh: "害怕、恐怕(n) 畏懼、害怕、擔心(vt)" },
  { id: 1155, en: "produce", zh: "生產、製造、產生(vt) 農產品(n)" },
  { id: 1156, en: "rat", zh: "鼠、叛徒(n)" },
  { id: 1157, en: "handkerchief", zh: "手帕(n)" },
  { id: 1158, en: "ketchup", zh: "蕃茄醬(n)" },
  { id: 1159, en: "roller skating", zh: "輪式溜冰(n)" },
  { id: 1160, en: "effective", zh: "有效的、被實施的、給人深刻印象的、有力的(adj)" },
  { id: 1161, en: "triangle", zh: "三角板(n)" },
  { id: 1162, en: "electricity", zh: "電(n)" },
  { id: 1163, en: "expensive fruit", zh: "高級水果、昂貴的水果(n)" },
  { id: 1164, en: "tiny", zh: "極小的、微小的(adj)" },
  { id: 1165, en: "children", zh: "一個以上的孩童、child 的複數(n)" },
  { id: 1166, en: "bit", zh: "一點、一些(n)" },
  { id: 1167, en: "eagle", zh: "鷹(n)" },
  { id: 1168, en: "anywhere", zh: "任何地方、無論哪裡(pron)" },
  { id: 1169, en: "hire", zh: "雇傭、租用(vt)" },
  { id: 1170, en: "confuse", zh: "使混亂(vt)" },
  { id: 1171, en: "a lot of", zh: "許多(片)" },
  { id: 1172, en: "kindergarten", zh: "幼稚園(n)" },
  { id: 1173, en: "tongue", zh: "舌頭、語言(n)" },
  { id: 1174, en: "dryer", zh: "烘乾機(n)" },
  { id: 1175, en: "symbol", zh: "象徵、符號、標誌(n)" },
  { id: 1176, en: "clap", zh: "拍手、拍、輕敲(v)" },
  { id: 1177, en: "appearance", zh: "出現、露面、外貌、外觀(n)" },
  { id: 1178, en: "Taichung", zh: "台中(n)" },
  { id: 1179, en: "chin", zh: "下巴、下頷(n)" },
  { id: 1180, en: "twice", zh: "兩倍、兩次(adv)" },
  { id: 1181, en: "captain", zh: "上尉、隊長、船長、機長(n)" },
  { id: 1182, en: "difficulty", zh: "困難、難事(n)" },
  { id: 1183, en: "disappear", zh: "消失、看不見、失蹤(v)" },
  { id: 1184, en: "scientist", zh: "科學家(n)" },
  { id: 1185, en: "Valentine's Day", zh: "西洋情人節(n)" },
  { id: 1186, en: "turtle", zh: "海龜、龜、甲魚、玳瑁(n)" },
  { id: 1187, en: "shopping", zh: "購物(n)" },
  { id: 1188, en: "carefully", zh: "小心地(adv)" },
  { id: 1189, en: "eyebrow", zh: "眉毛(n)" },
  { id: 1190, en: "contain", zh: "包含、容納(vt)" },
  { id: 1191, en: "skin", zh: "皮(膚) 外皮(n)" },
  { id: 1192, en: "behave", zh: "行為、表現、舉止(vt)(機器等)運轉(vi)" },
  { id: 1193, en: "flu", zh: "流行性感冒(等於influenza)(n)" },
  { id: 1194, en: "company", zh: "公司、同伴、陪伴(n)" },
  { id: 1195, en: "broadcast", zh: "廣播、播音(vi) 廣播、播音(n)" },
  { id: 1196, en: "niece", zh: "侄女、外甥女(n)" },
  { id: 1197, en: "stove", zh: "爐、火爐、電爐(n)" },
  { id: 1198, en: "tidy", zh: "整潔的、整齊的(adj)" },
  { id: 1199, en: "badminton", zh: "羽毛球(n)" },
  { id: 1200, en: "milk shake", zh: "奶昔(n)" },
  { id: 1201, en: "lane", zh: "小路、小徑(n)" },
  { id: 1202, en: "firm", zh: "商行、公司(n) 結實的、堅固的(adj)" },
  { id: 1203, en: "skating", zh: "滑冰、溜冰(n)" },
  { id: 1204, en: "drama", zh: "戲劇、劇本(n)" },
  { id: 1205, en: "oops", zh: "噢！(等於whoops)(interj)" },
  { id: 1206, en: "trumpet", zh: "喇叭、號(n)" },
  { id: 1207, en: "fellow", zh: "人、人員、研究員、[口語]傢伙、小夥子(n) 同伴的(adj)" },
  { id: 1208, en: "selfish", zh: "自私的、自利的(adj)" },
  { id: 1209, en: "chemical", zh: "化學的(adj)" },
  { id: 1210, en: "wow", zh: "哎喲、哇(interj)" },
  { id: 1211, en: "gentle", zh: "和藹的、溫和的、輕柔的、徐緩的(adj)" },
  { id: 1212, en: "tangerine", zh: "椪柑、橘(n)" },
  { id: 1213, en: "upstairs", zh: "在樓上、往樓上(adv) 樓上的(adj)" },
  { id: 1214, en: "hike", zh: "遠足、飛起、步行(v) 遠足、增加(n)" },
  { id: 1215, en: "intelligent", zh: "有智力的、有理解力的(adj)" },
  { id: 1216, en: "instant noodle", zh: "速食麵、泡麵、方便麵(n)" },
  { id: 1217, en: "brick", zh: "磚、積木(n)" },
  { id: 1218, en: "watermelon", zh: "西瓜(n)" },
  { id: 1219, en: "pipe", zh: "管子、管道、煙斗(n) 用管道輸送(vt)" },
  { id: 1220, en: "print", zh: "印刷、出版(vt) 印刷、印刷品、字體(n)" },
  { id: 1221, en: "soap", zh: "肥皂(n)" },
  { id: 1222, en: "salesman", zh: "銷售員(n)" },
  { id: 1223, en: "grandson", zh: "孫子、外孫(n)" },
  { id: 1224, en: "regard", zh: "看待、把…視為(vt) [複]敬意、問候(n)" },
  { id: 1225, en: "freezer", zh: "冷凍裝置、電冰箱、製冰機(n)" },
  { id: 1226, en: "horrible", zh: "恐怖的(adj)" },
  { id: 1227, en: "engineer", zh: "工程師、技師(n) 設計、建造(v)" },
  { id: 1228, en: "cafeteria", zh: "自助餐廳(n)" },
  { id: 1229, en: "flow", zh: "流(動) 垂、飄浮(vi) 流、流量(n)" },
  { id: 1230, en: "metal", zh: "金屬的(adj)" },
  { id: 1231, en: "form", zh: "形式、形狀、表格(n) 形成、組成(vt)" },
  { id: 1232, en: "prize", zh: "獎(賞) 獎品、獎金(n) 珍視、珍惜(vt)" },
  { id: 1233, en: "degree", zh: "程度、度數、學位(n)" },
  { id: 1234, en: "act", zh: "行動、做(vi) 行為、動作、法令(n)" },
  { id: 1235, en: "doughnut", zh: "甜甜圈(n)" },
  { id: 1236, en: "chapter", zh: "(書籍)章(n)" },
  { id: 1237, en: "bomb", zh: "炸彈(n)" },
  { id: 1238, en: "tip", zh: "頂、尖端、梢、傾斜、輕擊、末端、小費、秘密消息(n) 在…頂端裝附加物、使傾斜、使翻倒、暗示、輕擊、給、洩漏、給小費(vt)" },
  { id: 1239, en: "exit", zh: "出口(n)" },
  { id: 1240, en: "Los Angeles", zh: "洛杉磯(n)" },
  { id: 1241, en: "couple", zh: "夫妻、一對、一雙、兩三個、一些(n) 連接、結合(vt)" },
  { id: 1242, en: "document", zh: "公文、文件、文檔、檔案、文獻(n) 證明(v)" },
  { id: 1243, en: "reply", zh: "回答、答覆(n) 回答、答覆(v)" },
  { id: 1244, en: "mad", zh: "發病的、瘋狂的、惱火的、狂怒的(adj)" },
  { id: 1245, en: "main", zh: "主要的、最重要的(adj)" },
  { id: 1246, en: "oneself", zh: "自己、自身、親自、本人(pron)" },
  { id: 1247, en: "government", zh: "政府、治理、管理(n)" },
  { id: 1248, en: "curtain", zh: "簾、窗簾、門簾、幕(n)" },
  { id: 1249, en: "travel", zh: "旅行、行進(vi) 旅行(n)" },
  { id: 1250, en: "seek", zh: "尋找、追求(v)" },
  { id: 1251, en: "nearly", zh: "幾乎、差不多(adv)" },
  { id: 1252, en: "everywhere", zh: "到處、無論何處(adv)" },
  { id: 1253, en: "credit card", zh: "信用卡(n)" },
  { id: 1254, en: "napkin", zh: "餐巾、尿布、衛生棉(n)" },
  { id: 1255, en: "rent", zh: "租金(n) 租用(vt) 出租(vi)" },
  { id: 1256, en: "former", zh: "在前的、以前的(adj) 前者(n)" },
  { id: 1257, en: "focus", zh: "(使)聚焦、使(集中)(v) 焦點(注意、活動、興趣等的)中心(n)" },
  { id: 1258, en: "underlie", zh: "位於…的下面(v)" },
  { id: 1259, en: "London", zh: "倫敦(n)" },
  { id: 1260, en: "closet", zh: "壁櫥、小櫥(n)" },
  { id: 1261, en: "valley", zh: "山谷(n)" },
  { id: 1262, en: "police officer", zh: "警官(n)" },
  { id: 1263, en: "terrible", zh: "可怕的、駭人的(adj)" },
  { id: 1264, en: "lady", zh: "淑女、貴婦、夫人、小姐(n)" },
  { id: 1265, en: "shot", zh: "(shoot的過去式個過去分詞)(v) 開槍、射擊、射門、投籃(n)" },
  { id: 1266, en: "gold", zh: "金、黃金(n)" },
  { id: 1267, en: "alarm", zh: "警報(n)" },
  { id: 1268, en: "fit", zh: "適合、合身(vt) 適合、符合(vi)" },
  { id: 1269, en: "attention", zh: "注意、留心(n)" },
  { id: 1270, en: "exam", zh: "(口語)考試(n)" },
  { id: 1271, en: "flower shop", zh: "花店(n)" },
  { id: 1272, en: "pencil box", zh: "鉛筆盒(n)" },
  { id: 1273, en: "fashionable", zh: "流行的、時髦的(adj)" },
  { id: 1274, en: "tear", zh: "眼淚(n) 撕裂、撕破(v)" },
  { id: 1275, en: "koala", zh: "無尾熊(n)" },
  { id: 1276, en: "pingpong", zh: "乒乓球(n)" },
  { id: 1277, en: "possessive", zh: "擁有的(adj)" },
  { id: 1278, en: "level", zh: "水平、等級、水平面(n)" },
  { id: 1279, en: "Europe", zh: "歐洲(n)" },
  { id: 1280, en: "maximum", zh: "最大限度、最大量(n) 最高的、最大的(adj)" },
  { id: 1281, en: "locker", zh: "(有鎖的)小櫥櫃(n)" },
  { id: 1282, en: "ordinary", zh: "一般的、普通的、平淡的(adj)" },
  { id: 1283, en: "lightning", zh: "閃電(n)" },
  { id: 1284, en: "culture", zh: "文化、教養、修養(n)" },
  { id: 1285, en: "consider", zh: "認為、把…看作、考慮、細想(vt) 考慮、細想(over)(vi)" },
  { id: 1286, en: "Republic of China", zh: "中華民國(n)" },
  { id: 1287, en: "plate", zh: "盤子、盆子、平板(n) 鍍上(vt)" },
  { id: 1288, en: "men's room", zh: "男廁(n)" },
  { id: 1289, en: "best", zh: "最好的(adj) 最好地(adv)" },
  { id: 1290, en: "pigeon", zh: "鴿子(n)" },
  { id: 1291, en: "fancy", zh: "奇特的、異樣的(adj) 愛好、迷戀、想像力(n)" },
  { id: 1292, en: "soy-sauce", zh: "醬油(n)" },
  { id: 1293, en: "debt", zh: "債務、罪過(n)" },
  { id: 1294, en: "return", zh: "返回、歸來(複)受益(n) 歸還、送還、回報(vt)" },
  { id: 1295, en: "exist", zh: "存在(vi)" },
  { id: 1296, en: "bucket", zh: "水桶、桶(n)" },
  { id: 1297, en: "slender", zh: "細長的、修長的、苗條的(adj)" },
  { id: 1298, en: "lock", zh: "鎖(n) 鎖(被)鎖上(v)" },
  { id: 1299, en: "stormy", zh: "暴風雨的、暴躁的、激烈的(adj)" },
  { id: 1300, en: "jazz", zh: "爵士樂、爵士舞(n)" },
  { id: 1301, en: "feeling", zh: "感覺(n)" },
  { id: 1302, en: "verb", zh: "動詞(n)" },
  { id: 1303, en: "soft drink", zh: "碳酸飲料、不含酒精飲料(n)" },
  { id: 1304, en: "plant", zh: "植物、工廠(n) 種植(vt)" },
  { id: 1305, en: "midnight", zh: "午夜(n)" },
  { id: 1306, en: "service", zh: "服務、效勞(n) 維修、保養(vt)" },
  { id: 1307, en: "woods", zh: "樹林、森林(n)" },
  { id: 1308, en: "furniture", zh: "傢俱(n)" },
  { id: 1309, en: "speech", zh: "說話、言語、演說、講話、發言(n)" },
  { id: 1310, en: "greet", zh: "問候、招呼、迎接、對…報(以)(vt)" },
  { id: 1311, en: "Philippines", zh: "菲律賓(n)" },
  { id: 1312, en: "especially", zh: "特別、尤其、格外(adv)" },
  { id: 1313, en: "interview", zh: "接見、面試(n) 接見、會見(vt)" },
  { id: 1314, en: "thus", zh: "如此、這樣、因此(adv)" },
  { id: 1315, en: "duty", zh: "職責、責任、義務;(複)關稅(n)" },
  { id: 1316, en: "rise", zh: "起立、起身、起床(v)" },
];
